### ISSUE TITLE
Section for Upload file

### ISSUE THREAD

**Issue by anthowm** [kamilkisiela/apollo-angular#1030]
I do not know if you can add a section on how to upload a file using the client with angle. I think it would be helpful for other developers to find the answer faster.
There are the examples for the server and apollo client
Apollo Server:
https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs
Apollo Angular Client
https://github.com/mrdulin/angular-apollo-starter/blob/master/src/app/graphql/graphql.module.ts

**Comment by kamilkisiela** [comment]
PR welcome, I can guide and help whenever you would need any help :)

**Comment by kamilkisiela** [comment]
We have a mention of file uploads in documentation now.
