### ISSUE TITLE
Update apollo-angular-cache-ngrx patch version on npm registry

### ISSUE THREAD

**Issue by adgoncal** [kamilkisiela/apollo-angular#1036]
## Feature request

Bump apollo-angular-cache-ngrx version after each commit, and push to npm registry.

## The problem:

I want to update an Angular app to use Angular 7. However, I am currently on the latest version of apollo-angular-cache-ngrx (1.0.0-beta.2), which has a lock on the peerDependencies in package.json: `"@angular/core": "^6.1.0"` and `"@ngrx/store": "^6.0.0"`.

I see that package.json for apollo-angular-cache-ngrx was updated on Oct 19, 2018 to support Angular 7, but this was never tagged on the npm registry.

https://github.com/apollographql/apollo-angular/commit/5fb0d891431218937501fb590f9bfdf167db64b0#diff-876a9c1dc72e73a7ecdec303cc5424feR29

Furthermore, I see that there were multiple commits with dependency updates since then, which were also not tagged.

**Comment by kamilkisiela** [comment]
There's too much changes in the `apollo-cache-inmemory` since v1.3 then we don't support ngrx cache any longer.

#886

If you want to submit a PR that passes tests and everything then I'm open for publishing it.

**Comment by adgoncal** [comment]
I see... 
It would be nice to add a deprecation warning to the README for `apollo-angular-cache-ngrx` linking to #886.
