### ISSUE TITLE
Deprecated codegen command still used in docs

### ISSUE THREAD

**Issue by JakeDawkins** [kamilkisiela/apollo-angular#1169]
The docs for this still use the old `apollo-codegen` command which should be replaced with `apollo client:codegen`. We should update the docs to reflect the new codegen commands

https://github.com/apollographql/apollo-angular/blob/master/docs/source/features/developer-tooling.md#apollo-codegen

**Comment by fetis** [comment]
new documentation, new codegen 
https://apollo-angular.com/docs/development-and-testing/developer-tools#code-generation
