### ISSUE TITLE
With "buildOptimizer": true, build crushes

### ISSUE THREAD

**Issue by maxim1006** [kamilkisiela/apollo-angular#1226]
**Intended outcome:**

if you set ""buildOptimizer": true" in angular.json and try ng build --prod,
then you'll get an error:

core.js:19790 ERROR Error: Uncaught (in promise): ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new Y (ng.apollo.js:136)
    at core.js:26806
    at ji (core.js:26769)
    at Ni (core.js:26716)

**Actual outcome:**

![image](https://user-images.githubusercontent.com/3056353/58956132-4eed3480-87a6-11e9-9079-a14ec3d638b9.png)

**How to reproduce the issue:**

set ""buildOptimizer": true" in angular.json and try ng build --prod,

**Versions**

angular - 7.2.15
"apollo-angular@1.6.0",
"graphql@^14.3.1",
"typescript@3.1.6",

**Comment by kamilkisiela** [comment]
We have an app on Angular 7 running on latest Apollo. Could you create a small reproduction?

**Comment by carnun** [comment]
We've had the same issue on our app with a dataservice that relies on Apollo failing. Here's the error:

**Comment by sedenko93** [comment]
We encounter the same error, probably you already have this information by now, but just sharing.

i've noticed this is only happening if the build target is es6 in the tsconfig. Its related to this issue https://github.com/angular/angular-cli/issues/14416. Is it possible to provide a fix for this issue? Or we better use apollo-angular 1.5.0 untill we upgrade to angular 8?
