### ISSUE TITLE
testing: .networkError doesn't trigger an error callback

### ISSUE THREAD

**Issue by fetis** [kamilkisiela/apollo-angular#1238]
**Intended outcome:**
I'm trying to test the behavior of my Angular service on an error condition. Here's the simplifed code

```typescript
// in service
this.apollo.query(..).subscribe(()=> {}, error => console.log(error))
...
// in test
backend
  .expectOne('xxx')
  .networkError(new Error('500'));
```

I'm expecting the error callback to be triggered and log an error.

**Actual outcome:**
It never triggers. After some stack-tracing, I see what's happening.
1. `networkError` fills `ApolloError` object and pass it to `flush` method on TestingController
2. `flush` checks that it's error and call `this.observer.error(result);` it somehow triggers an exeception
3. this exception is catched in `catch` section of  `QueryManager.fetchRequest`  promise and re-thrown. it's in apollo-client;
4. it's catched again by inner part of `fetchRequest` and re-thrown again
5. it's catchec by `finally` section of `Zone.run` and died without any message logging.

I'm not sure what causes this behavior. 

**Versions**
apollo-angular@1.6.0
apollo-client@2.5.1
typescript@3.4.5
@angular/core@8.0.0
graphql@0.13.2

**Comment by kamilkisiela** [comment]
Could you provide an example / reproduction?

https://github.com/apollographql/apollo-angular/commit/ff96b940218a32d5ba9eca370cff22f1fcd87ae0 seems to be OK

**Comment by fetis** [comment]
on the fresh ng8 application it works fine. I need to investigate more.
