### ISSUE TITLE
Update normalization docs with a clearer explanation and example

### ISSUE THREAD

**Issue by ChrisBates** [kamilkisiela/apollo-angular#1242]
In the following doc: https://www.apollographql.com/docs/react/advanced/caching/#normalization

In regards to the key'ing off of different fields using `dataIdFromObject`, the docs mention:
```
Note that Apollo Client doesn't add the type name to the cache key when you specify a custom dataIdFromObject, so if your IDs are not unique across all objects, you might want to include the __typename in your  dataIdFromObject.
```

I find the explanation (and example) doesn't really highlight the significance of what this means, after I personally implemented a `dataIdFromObject` that was mapping keys for various objects like:
```
dataIdFromObject: obect => {
  switch (object.__typename) {
    case 'foo': return object.fooId;
    case 'bar': return object.barId;
    default: return defaultDataIdFromObject(object);
  }
}
```

This was causing my Foo and Bar objects to be normalized to integers, and conflicting/overriding each other. It was only through inspecting the cache and watching queries did I figure out what the docs were really trying to say.

I think it's worth elaborating on the fact that Apollo doesn't add the type name to the cache key when using a custom `dataIdFromObject`, and that *failing to include it yourself* will potentially cause cache conflicts.

**Comment by kamilkisiela** [comment]
Closing, `dataIdFromObject` is deprecated now
