### ISSUE TITLE
Docs Sample code needs updating, example repo links are broken

### ISSUE THREAD

**Issue by ThomasHeliase** [kamilkisiela/apollo-angular#1311]
**Intended Outcome**

A working reference example, and sample code for implementing pagination code in Angular.

**Actual Outcome**
From [pagination recipe documentation page](https://www.apollographql.com/docs/angular/recipes/pagination/) there are numerous issues, 
the primary issue is that there is no working sample code linked.

All of the GitHunt example references on the page go nowhere (404 on github).

Additionally The syntax on the inline example isn't correct / up to date:
e.g. `forceFetch: true` isn't working (should it  be `fetchPolicy: ''`?)
and the `data` references from the subscribe method are not recognized, either with typed  /untyped returns.

This would be kind of OK if the referenced sample project was working - but it doesn't.

I'm currently trying to implement Apollo pagination in Angular 8, still struggling to get working (trying to wire to ag-grid infinite scroll - grrrr) and was hoping to see a working example:

I hope an example of working pagination can be provided and the example code brought up to date.  I am not familiar enough with the deprecated items to provide this myself.

**How to Reproduce**
navigate to [angular pagination docs](https://www.apollographql.com/docs/angular/recipes/pagination/), 
attempt to build code from example or navigate to the linked project.

**Comment by kamilkisiela** [comment]
Fixed
