### ISSUE TITLE
bug: QueryRef#options not present in 1.7.0 build

### ISSUE THREAD

**Issue by thefliik** [kamilkisiela/apollo-angular#1324]
**Intended outcome:**

Version 1.7.0 of `apollo-angular` contains typings for `QueryRef` with a public `options` property. I'd like to access that property.

**Actual outcome:**

The distributed build for version 1.7.0 of `apollo-angular` does not contain a public options property on `QueryRef`. The typings do declare the property, but it doesn't actually exist in the code and attempting to access it returns `undefined`.

**How to reproduce the issue:**

https://stackblitz.com/edit/simple-apollo-angular-example

Open up the console to inspect `QueryRef` object. It lacks an `options` property.

**Versions**

1.7.0

**Comment by mezhik91** [comment]
Is there any updates on this? I have the same issue.. also the same happens for properly “variables”.

**Comment by kamilkisiela** [comment]
fixed on latest
