### ISSUE TITLE
Apollo tests fail with --codeCoverage but pass without

### ISSUE THREAD

**Issue by aaraggornn** [kamilkisiela/apollo-angular#1341]
**Intended outcome:**
Running `ng test --codeCoverage=true --no-watch` should pass, since running without `--codeCoverage` passes

**Actual outcome:**
The test fails with `TypeError: Cannot read property 'use' of undefined` this looks to be in (http://localhost:9877/_karma_webpack_/node_modules/apollo-angular/fesm2015/ngApollo.js:239:1). It seems Apollo is not being injected correctly.

**How to reproduce the issue:**
When testing a `Query` from apollo-angular in a service (not a component) the tests will pass when run normally but will fail when generating code coverage. See the repository at [https://github.com/aaraggornn/apollo-error-test](https://github.com/aaraggornn/apollo-error-test) for a reproduction.

Run `npm run test` to pass and `npm run test:cc` to fail (using --codeCoverage)

**Versions**
"apollo-angular": "^1.7.0",
"apollo-client": "^2.6.4",
"typescript": "~3.5.3",
"@angular/core": "~8.2.8",
"graphql": "^14.5.8",
"graphql-tag": "^2.10.1",

**Comment by aaraggornn** [comment]
This also happens with apollo-angular 1.8.0

**Comment by nicky-lenaers** [comment]
Just curious: any workaround available (as this currently blocks generating coverage reports)?

**Comment by nicky-lenaers** [comment]
I noticed the error comes from [this line](https://github.com/apollographql/apollo-angular/blob/master/packages/apollo-angular/src/Mutation.ts#L20), where `this.apollo` is referenced and its method `use()` is invoked (this causes the error apparently).

I don't know why this happens only when code coverage is enabled, but hopefully this info helps for debugging the problem a bit faster.

**Comment by nicky-lenaers** [comment]
@aaraggornn I have found a temporary workaround. You'll need to inject `Apollo` manually in the extended `Mutation` class and call `super()` with the provided apollo instance:

```ts
import { Injectable } from '@angular/core';
import { Mutation, Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

@Injectable({ providedIn: 'root' })
export class SomeMutationGQL extends Mutation {

  constructor(apollo: Apollo) {
    super(apollo); // <-- use this to prevent  the error from throwing
  }

  public document = gql`
    mutation ...
  `;
}
```

It will work with `--codeCoverage` turned on.

**Comment by havran** [comment]
Hi. I have same problem with using apollo-graphql with Angular 9.

**Comment by LukasMachetanz** [comment]
We have the same strange problem in our project. Please fix.

**Comment by johnnyomair** [comment]
Our solution was to ignore generated GraphQL types for the coverage. Perhaps this is related to the instrumentation of the generated code.

```diff
// https://github.com/thymikee/jest-preset-angular#brief-explanation-of-config
module.exports = {
  preset: 'jest-preset-angular',
  roots: ['src'],
  setupFilesAfterEnv: ['<rootDir>/src/setup-jest.ts'],
  moduleNameMapper: {
    '@app/(.*)': '<rootDir>/src/app/$1',
    '@assets/(.*)': '<rootDir>/src/assets/$1',
    '@core/(.*)': '<rootDir>/src/app/core/$1',
    '@env': '<rootDir>/src/environments/environment',
    '@src/(.*)': '<rootDir>/src/src/$1',
    '@state/(.*)': '<rootDir>/src/app/state/$1',
  },
  transformIgnorePatterns: ['node_modules/(?!(jest-test))'],
  coverageReporters: ['html', 'text'],
+ coveragePathIgnorePatterns: ['/node_modules/', 'src/app/modules/graphql/types/generated.ts'],
};
```

Hope this helps.

**Comment by josh18** [comment]
Seems like it is caused by this issue https://github.com/angular/angular/issues/31337
