### ISSUE TITLE
Documentation or Implementation for Disabling SSL Verification

### ISSUE THREAD

**Issue by julmot** [kamilkisiela/apollo-angular#1354]
Currently, in my `graphql.module.ts` file I'm returning my Apollo instance like that:

```js
export function createApollo(httpLink: HttpLink) {
  return {
    link: httpLink.create({
      uri
    }),
    cache: new InMemoryCache(),
  };
}
```

This only works when the specified `uri` has a SSL certificate. In my case, it's a self-signed certificate, which makes the request fail with status code `0 Unknown error`.

So, I can currently work around the problem with:

```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
```

But isn't there a better way like [this one](https://github.com/apollographql/apollo-link/issues/229#issuecomment-347855361) (when using Next.js)?

**Comment by kamilkisiela** [comment]
I don't see how it's related to Apollo. HttpLink uses `HttpClient` under the hood and only that so it's pure Angular's HttpClient thing.

**Comment by julmot** [comment]
Yes, that might be the case. That's why I've referenced the angular issue and mentioned in the subject that this issue can also be about a documentation improvement in this regard. I think it's a common use case to consume data from a dev server during development with a self signed certificate.
