### ISSUE TITLE
Apollo has a constructor which is not compatible with Dependency Injection. It should probably not be @Injectable().

### ISSUE THREAD

**Issue by Napas** [kamilkisiela/apollo-angular#1376]
I was following documentation from the https://www.apollographql.com/docs/angular/basics/setup/ trying to install Apollo Angular.

After running `ng add apollo-angular`  and updating API endpoint in the `graphql.module.ts`, I'm getting ` Apollo has a constructor which is not compatible with Dependency Injection. It should probably not be @Injectable().`  when trying to inject `Apollo` from `apollo-angular` in any component or service.

Angular version: `8.2.11`
Angular Apollo version: `1.8.0`

How this could be resolved?

**Comment by wSedlacek** [comment]
This issue only shows up for me when `"angularCompilerOptions": { "enableIvy": false },`
Hope it can be resolved soon!

**Comment by sidymbengue25** [comment]
having the same issue

**Comment by TamirShklaz** [comment]
Likewise

**Comment by sidymbengue25** [comment]
Hope we found a solution soon, because lot of project lay on that (Apollo-client + Angular).

**Comment by jogelin** [comment]
Same issue for me...

This error look like something that could be related to (https://next.angular.io/guide/ivy-compatibility)
> All classes that use Angular DI must have an Angular decorator like @Directive() or @Injectable (previously, undecorated classes were allowed if an ancestor class or subclass had a decorator).



May this library could help to validate apollo ?!: https://github.com/angular/ngcc-validation

**Comment by CharlieGreenman** [comment]
Anyone working on this?

**Comment by sidymbengue25** [comment]
It’s taking time. We need to fix that

**Comment by Vilsol** [comment]
This problem goes away if you switch to angular 9.0.0 RC releases, e.g. `9.0.0-rc.2`

**Comment by kamilkisiela** [comment]
There's no stable Angular 9 yet so you guys please give me time to solve it. I started creating `apollo-angular` when Angular was in alpha, then in beta and then they changed bunch of stuff in one of RCs.

As @Vilsol pointed out. It's no longer an issue in `9.0.0-rc.2`.

It's an open-source project and I'm the only one developing it (Apollo Team haven't pushed a single line of code). If you want to help, please provide reproductions or even pull requests, this speeds up things a lot.

**Comment by joacorandom** [comment]
There is some way to help you with this fix? Can you give me some pointers around this?
I need to fix this soon and I'm willing to help to get this quickier.

**Comment by kamilkisiela** [comment]
@joacorandom You could create a repository with basic reproduction

**Comment by joacorandom** [comment]
Here it is.

https://bitbucket.org/cocha-digital/angular-apollo-ivy/src/master/

**Comment by wSedlacek** [comment]
@kamilkisiela I want to personally thank you for all your work. This project is awesome. I really do appreciate you taking the time to look into this. Thank you.

**Comment by Nielsb85** [comment]
I am only having this issue when running unit tests. is there any solution for this already?

**Comment by PowerKiKi** [comment]
According to https://github.com/apollographql/apollo-angular/issues/1466#issuecomment-612029092, https://github.com/apollographql/apollo-angular/issues/1466#issuecomment-613171002 and https://github.com/apollographql/apollo-angular/issues/1376#issuecomment-555808651. It seems it's been resolved and this issue should be closed.

**Comment by Maximaximum** [comment]
Seems like the issue hasn't been fixed yet. I'm still facing it with Angular 12

**Comment by Maximaximum** [comment]
@kamilkisiela could you please reopen this one?

**Comment by WolfSoko** [comment]
Maybe it is due to a missing `@Injectable` decorator at the BaseApollo class.

**Comment by Maximaximum** [comment]
@WolfSoko No, as I've found out, this issue is caused by a bug in `jest-preset-angular`, which is not able to properly handle es6 namespace imports. And such imports are (in my case) generated by `graphql code generator`. This is the issue: https://github.com/thymikee/jest-preset-angular/issues/963

@Nielsb85 @CharlieGreenman @Napas could you please confirm if you were experiencing this issue when using jest with angular?

**Comment by Nielsb85** [comment]
Yes. I was using jest with Angular

Op do 9 sep. 2021 12:50 schreef Maksym Kobieliev ***@***.***>:

**Comment by WolfSoko** [comment]
@Maximaximum Good to know. I can confirm that I  have the DI Problems when using jest and the generated  queries from graphql code generator.
