### ISSUE TITLE
Support Apollo Client v3

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/apollo-angular#1380]

**Comment by MrGekko** [comment]
Looks like allot of progress has been made over at https://github.com/apollographql/apollo-client/blob/release-3.0/ is this sufficient to start implementing 3.0?

**Comment by kamilkisiela** [comment]
I'm working on it here #1383. I think it's fairly stable to start using Apollo Client v3. You can expect an alpha release this weekend.

**Comment by witcotech-admin** [comment]
Any chance that the observable variables from v1 that were dropped in v2 (#425) might get re-implemented for v3? :)

**Comment by MicMicMon** [comment]
Interesting update with the caching system, might be interesting to see how it fits with angular wrapper: https://github.com/apollographql/apollo-feature-requests/issues/5

**Comment by Eraldo** [comment]
Is this package still actively maintained?
What is the suggested way of combining apollo v3 and angular?

**Comment by kamilkisiela** [comment]
@Eraldo is Apollo Client v3 out already? Once it's out, there will be a major version of Apollo Angular too

**Comment by Eraldo** [comment]
I am super glad to hear that. 
Thank you @kamilkisiela. 😄

**Comment by mattwilson1024** [comment]
Apollo Client 3.0 has been officially released now 🎉 

[Blog Announcement](https://www.apollographql.com/blog/announcing-the-release-of-apollo-client-3-0/)
[Github Release](https://github.com/apollographql/apollo-client/releases/tag/v3.0.0)

Pleased to hear that there will be a new version of Apollo Angular, will be great to have access to the new caching features.

**Comment by charsleysa** [comment]
@kamilkisiela is #1383 able to be merged or will a new PR be needed?

**Comment by KeithGillette** [comment]
The Apollo team published [Apollo Client 3.1](https://github.com/apollographql/apollo-client/blob/v3.1.0/CHANGELOG.md#apollo-client-310) today. Any timeline for an Apollo Angular release supporting v3?

**Comment by d2kx** [comment]
There is a PR open that supports AC3 (now released as apollo-angular@2.0.0-beta.3) here: https://github.com/kamilkisiela/apollo-angular/pull/1383

Please help testing it and giving feedback if you can! @KeithGillette @charsleysa

**Comment by intellix** [comment]
@kamilkisiela it looks like you forgot to push the tag for `apollo-angular-link-persisted@2.0.0`

**Comment by kamilkisiela** [comment]
@intellix `apollo-angular-link-persisted` wasn't updated, I changed its version by mistake :(

**Comment by intellix** [comment]
Tried updating and fixed all of the type errors but just ended up with a WSOD (White Screen of Death) with the tab freezing with 150% CPU and was unable to even profile why. Guess I'll wait for other people to try it out

**Comment by JesseZomer** [comment]
> The Apollo team published [Apollo Client 3.1](https://github.com/apollographql/apollo-client/blob/v3.1.0/CHANGELOG.md#apollo-client-310) today. Any timeline for an Apollo Angular release supporting v3?

Also interested in this. This as a feature that allows me to workaround this bug: https://github.com/apollographql/apollo-client/issues/6760 

basically 'cache-and-network' fetchpolicies now do a network request everytime something updates the query. I have a page where I do a few local mutations and update a query. This then gets overwritten by the network request data coming in.
3.1 gives us the setting `nextFetchPolicy` which allows us to get the old 'cache-and-network' behaviour back (more here: https://github.com/apollographql/apollo-client/issues/6760#issuecomment-668188727)
