### ISSUE TITLE
Impossible to refetchQueries with multiple client

### ISSUE THREAD

**Issue by dilame** [kamilkisiela/apollo-angular#1459]
**Intended outcome:**

I just want to refetchQueries, but my mutation executes on client `foo` and query should be executed on client `bar`, but refetchQueries accepts only documents that doesnt contain any info about client.

**Actual outcome:**
both requests executes on client `foo`

**Comment by kamilkisiela** [comment]
It's something I can't do in Apollo Angular codebase. I would need a way to do it in Apollo Client itself first and then connect it here, in angular integration.
