### ISSUE TITLE
How to access loading in mutation result?

### ISSUE THREAD

**Issue by qortex** [kamilkisiela/apollo-angular#1468]
I understand from apollo docs that mutations also return loading state, but I can't find how to access that from the Typescript types (`FetchResult` just has `data` & `errors`).

What am I missing there?

![image](https://user-images.githubusercontent.com/37897072/75089784-c7766a00-555c-11ea-9aab-ffecb2a4aecc.png)

**Comment by MicMicMon** [comment]
Went with my own for now:
```ts
    loading: fetch
        .pipe(
          map(_ => false),
          catchError(() => of(false)),
        )
        .pipe(startWith(true)),
```

where `fetch` holds my `Observable<FetchResult<P>>` object.

**Comment by attilacsanyi** [comment]
We are also interested, it seems like the [React lib](https://hasura.io/learn/graphql/angular-apollo/mutations-variables/3-create-mutation/) has an option to handle `loading`. This will be just a limitation here, thanks for any guideline.

**Comment by kamilkisiela** [comment]
bc223fe6487edd35c56ad908e4739580ce69f056
