### ISSUE TITLE
flushData method for testing

### ISSUE THREAD

**Issue by fetis** [kamilkisiela/apollo-angular#1469]
Hello, 

I find it very tedious to write in every test something like this
```
backend.expectOnce('opname').flush({
 data: {
  opname: {
    ...some data object
  }
 }
}
```

I want to introduce a shorthand method to flash data directly, like this
```
backend.expectOnce('opname').flushData({
  opname: {
  ....data obj
  }
})
```

what do you think about the proposal? if you're ok with it I'm willing to open a PR.

**Comment by kamilkisiela** [comment]
I like it

**Comment by fetis** [comment]
@kamilkisiela PR opened
