### ISSUE TITLE
Add support for Query using 'GET' method - apollo-angular-link-http

### ISSUE THREAD

**Issue by mbao01** [kamilkisiela/apollo-angular#1471]
Allow option to set the request method based on query type (Query or Mutation)

**Package**
apollo-angular-link-http

**Proposed**
Use `useGETForQueries` option to `httpLink.create({ . . ., useGETForQueries: true });`.
When `useGETForQueries` is `true`, use GET request for Query Type and POST request for Mutation Type

**Use case**
> If you want mutations to continue to be sent as non-idempotent POST requests, set the top-level useGETForQueries option to true instead of setting

> useGETForQueries: set to true to use the HTTP GET method for queries (but not for mutations)

Angular Service Worker (NGSW) only allows caching GET requests/response. This will allows caching apollo queries using NGSW.

_This feature is available https://www.apollographql.com/docs/link/links/http/_

**Comment by marcus-sa** [comment]
@kamilkisiela is this on the roadmap?

**Comment by maqlec** [comment]
I see that feature is in the codebase unreleased yet. When do you plan to release new version?
