### ISSUE TITLE
Broken link in console error

### ISSUE THREAD

**Issue by kasarda** [kamilkisiela/apollo-angular#1473]
There is a broken link in this error log when using apollo for angular:
`invariant.esm.js:29 You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types. Apollo Client will not be able to accurately map fragments. To make this error go away, use the `IntrospectionFragmentMatcher` as described in the docs: https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher`

**Comment by fetis** [comment]
I didn't find a proper angular link, but this looks like a replacement
https://www.apollographql.com/docs/react/data/fragments/

**Comment by fetis** [comment]
`IntrospectionFragmentMatcher` was removed in v2.0, so it's not relevant anymore
see https://apollo-angular.com/docs/migration#breaking-cache-changes for details
