### ISSUE TITLE
Unknown object type expected in context.headers.keys()

### ISSUE THREAD

**Issue by cdelgadob** [kamilkisiela/apollo-angular#1476]
**Intended outcome:**
Batched queries working normally

**Actual outcome:**
Exception this line [context.headers.keys().map((k: string) => context.headers.get(k));](https://github.com/apollographql/apollo-angular/blob/b2f8dfd2c2e6663a3521cc59b70cfe31addd87f3/packages/apollo-angular-link-http-batch/src/HttpBatchLink.ts#L153)
I don't know what type of object is expected here. I tried with a regular object, a Map and a Headers object.

**How to reproduce the issue:**
I set the headers with the `apollo-link-context` link to set the authorization header, which is the only header present.

**Versions**
     "@angular/common": "^9.0.4",
    "@angular/core": "^9.0.4",
    "@angular/forms": "^9.0.4",
    "@angular/platform-browser": "^9.0.4",
    "@angular/platform-browser-dynamic": "^9.0.4",
    "@angular/router": "^9.0.4",
    "apollo-angular": "^1.8.0",
    "apollo-angular-link-http-batch": "^1.7.0",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.8",
    "apollo-link-context": "^1.0.19",
    "apollo-link-error": "^1.1.12",
    "apollo-link-logger": "^1.2.3",
    "apollo-link-retry": "^2.2.15",
    "typescript": "~3.7.5"

**Comment by kamilkisiela** [comment]
it shouldn't be a problem in latest version
