### ISSUE TITLE
Invalidate query cache

### ISSUE THREAD

**Issue by piyushkothari3** [kamilkisiela/apollo-angular#1486]
Need a way to access all cache keys to delete from cache instead of having to clear all permutations of variable query has been used for.

Some data we fetch can get updated by some other user, so we have no way of updating cache using mutations, we need a way to clear cache related to particular query when we get some notification in signalR

**Comment by qortex** [comment]
There has been an interesting discussion [here](https://github.com/apollographql/apollo-feature-requests/issues/5).

Quite some time since I looked at it, but what I gathered is that it's not easy nor settled yet unfortunately.

**Comment by kamilkisiela** [comment]
It's something related to Apollo Client and its cache so I will close the issue but feel free to submit new issue or find similar one in apollo-client repository.
