### ISSUE TITLE
Importing ApolloModule causes side-effect of breaking RxJS in Yarn workspace

### ISSUE THREAD

**Issue by lars-berger** [kamilkisiela/apollo-angular#1504]
This bug was an absolute nightmare to track down. I'm running into the error `TypeError: You provided 'undefined' where a stream was expected` when using the RxJS `combineLatest` operator in a Yarn workspace when `ApolloModule` (or `HttpLinkModule`) is imported. 

**How to reproduce the issue:**

Issue can be reproduced [here](https://github.com/lars-berger/apollo-angular-error-repro).

In the `AppComponent.ts`, the following line throws an error (no graphql queries are involved):

```
combineLatest([matchingNode$]).subscribe((result) => console.log('Success!', result));
```

This only occurs when `ApolloModule` is imported.

```
@NgModule({
  /** Error is not thrown with these imports: */
  imports: [CommonModule, FormsModule, HttpClientModule, BrowserAnimationsModule],

  /** Error is thrown with these imports: */
  imports: [CommonModule, FormsModule, HttpClientModule, BrowserAnimationsModule, ApolloModule, HttpLinkModule],
})
export class CoreModule {}
```

One thing I noticed is that in the above repo, if `TreeNode` class is declared directly in `AppComponent.ts` the error is not thrown when `ApolloModule` is imported. 

I've tried [nohoisting ](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) every package and it doesn't make a difference. Also tried out Lerna with npm/yarn and the issue still crops up.

This seems to be related to the issue: https://github.com/lerna/lerna/issues/1451

**Versions**

Using the latest version of apollo/angular related packages. Running the latest version of yarn (`1.22.4`).
```
"@angular/core": "9.1.3",
"apollo-angular": "1.9.1",
"apollo-angular-link-http": "1.10.0",
"apollo-cache-inmemory": "1.6.5",
"apollo-client": "^2.6.8",
"apollo-link": "1.2.14",
"electron": "8.0.1",
"graphql": "14.6.0",
"graphql-tag": "2.10.3",
"rxjs": "6.5.5",
"typescript": "3.7.5",
```

**Comment by lars-berger** [comment]
Solved by adding the following to the angular polyfills file:
```JavaScript
if (!(Symbol as any).observable) {
  (Symbol as any).observable = Symbol('Symbol.observable polyfill from RxJS Testing');
}
```

**Comment by jeroenmaas** [comment]
Thanks for sharing this here. I had a different error: "TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable". Funny enough found another post of you at RxJS with the same error and solution. -> https://github.com/ReactiveX/rxjs/issues/5409

The workaround works great for my case. For others wondering more information about this issue can be found here https://ncjamieson.com/how-to-use-interop-observables/

Is this maybe something to add in the readme as a gotcha?
