### ISSUE TITLE
Network data is correct, data received is totally wrong

### ISSUE THREAD

**Issue by JacopoSciampi** [kamilkisiela/apollo-angular#1507]
I'm trying to get some data using Apollo. Here's the simple query: 

    export const CurrentUserForProfile = gql`
    
        query getGroupDetails($groupId: Long, $groupType: String, $tags: [Tag]) {
            nodes: NodesRelay (
              first: 50
              where: {
                tags: { CONTAINS: $tags },
                OR: {
                  AND: {
                    nsParentId: { EQ: $groupId }
                    nsParentType: { EQ: $groupType }
                  }
                  superGroupNodeLinks: {
                    groupId: { EQ: $groupId }
                    groupType: { EQ: $groupType }
                  }
                }
              }
            ) {
              elements {
                data {
                  ...nodeFields
                  ext {
                    ...nodeExtFields
                  }
                }
              }
              pageInfo {
                ...pageInfoFields
              }
            }
          }
        
          fragment nodeFields on Node {
            id {
              id
              type
            }
            subtype
            internalId
            businessId
            scadaId
            isGroup
            isTemporary
            nsParentId
            nsParentType
            ouId
            description
            shortDescription
            status
            isNsPowered
            tags
            owners
            notes
            version
          }
           
          fragment nodeExtFields on NodeExt {
            id {
              id
              type
            }
            asParentId
            asParentType
            isAsPowered
            isAsInconsistent
            isAsPoweredInParallel
            isAsPoweredByExtSource
            isAsPoweredByDiffSource
            maneuverId
            entityStatusMap
            createdAt
            createdBy
            updatedAt
            updatedBy
            version
          }
           
          fragment pageInfoFields on PageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
          }
        `;

and the way i'm using it is as the tutorial say: 

    this.data = this.apollo
                .watchQuery({
                    query: CurrentUserForProfile,
                    variables: {
                        "groupId": 15,
                        "groupType": "sec_subst",
                        "tags": ["GIS"]
                    },
                    fetchResults: true,
                    returnPartialData: false,
                }).valueChanges
                .pipe(
                    map((res: any) => res.data.nodes.elements)
                )

the HTML: 

    <ng-container *ngFor="let a of data | async">
        {{a.data.id.type}} <br>
      </ng-container>

What I'm getting is just 10 lines of `"lv_line"`.
If I change the logic, subscribing in the component and doing a `console.log(data)` I see the same things. This could be correct, but is not. The data I'm getting is totally wrong, and If I check in the network tab, no matter what the logic in my application is, the data is correct and is not just an array of 10 elements with a property `type` always being "lv_line".

Here's the network result: 

[![enter image description here][1]][1]

while the HTML result looks like this: 

[![enter image description here][2]][2]

What am I doing wrong? I've tried everything I could possibly think of without any success, getting the same wrong result try after try.

  [1]: https://i.stack.imgur.com/16iNi.png
  [2]: https://i.stack.imgur.com/tATLA.png

**Comment by JacopoSciampi** [comment]
I managed to fix that issue by simply using the `no-cache` fetchPolicy.

```
this.data = this.apollo
            .watchQuery({
                query: CurrentUserForProfile,
                variables: {
                    "groupId": 15,
                    "groupType": "sec_subst",
                    "tags": ["GIS"]
                },
                fetchResults: true,
                returnPartialData: false,
                fetchPolicy: "no-cache"

            }).valueChanges
            .pipe(
                map((res: any) => res.data.pippo.elements)
            )
```

**Comment by kamilkisiela** [comment]
I'm pretty sure it's related to Apollo Cache so please submit an issue [there](https://github.com/apollographql/apollo-client/issues/new/choose).
