### ISSUE TITLE
Loading state is not available during refetch

### ISSUE THREAD

**Issue by Filson14** [kamilkisiela/apollo-angular#1519]
**Intended outcome:**
While performing refetch, QueryRef.valueChanges stream should produce two "ticks". First with current data and _loading_ flag set to **true**, and second one with refetched data and _loading_ set to **false**.

**Actual outcome:**
Only one stream event happens with refetched data. _loading_ is always **false**

**How to reproduce the issue:**
Set _fetchPolicy_ to any variant other than default (in my case, "no-cache" or "network-only").
Perform watchQuery and subscribe to _valueChanges_ observable.

With default settings of the fetch policy, problem does not occur and _loading_ is set to true at start, and to false after response.

It can be related to #1189 where few people act like having the same problem.

I woudl be glad for any suggestions.

**Versions**
apollo-angular: 1.9.1 (found that problem with 1.6.0, update did not solve it)
apollo-client: 2.6.4
apollo-link: 1.2.12
apollo-cache-inmemory: 1.6.3

**Comment by stormwild** [comment]
@Filson14 

A possible workaround would be to set the loading to true by calling pipe before subscribe, `.valueChanges.pipe(o$ => { this.loading = true; return o$; })`.

```js
this.querySubscription = this.apollo.watchQuery<any>({
      query: CurrentUserForProfile
    })
      .valueChanges
      .pipe(o$ => { this.loading = true; return o$; })
      .subscribe(({ data, loading }) => {
        this.loading = loading;
        this.currentUser = data.currentUser;
      });
```

**Comment by kamilkisiela** [comment]
We have `useInitialLoading` flag to get the `loading: true` on the first run if data is not in the cache but setting `loading` for every refetch is something we did by design, fetching happens in the background while still serving data in the UI.
