### ISSUE TITLE
official docs chat link broken

### ISSUE THREAD

**Issue by Eraldo** [kamilkisiela/apollo-angular#1521]
Current behaviour:
Clicking on the `Discuss on Spectrum` link in the official docs links to:
https://spectrum.chat/apollo/apollo-angular
=> That link is broken.

If anything it should link to:
https://spectrum.chat/apollo/angular-apollo

When brings up bigger questions!:
What is the status of `apollo-angular` and its roadmap with regards to apollo v3?
The official support seems to dwindle and I don't feel comfortable about it's future. :|

**Comment by kamilkisiela** [comment]
We've got GitHub Discussions now so I'm closing this one
