### ISSUE TITLE
pass defaultOptions to create method

### ISSUE THREAD

**Issue by Diluka** [kamilkisiela/apollo-angular#1522]
Thanks for your interest in helping make Apollo Angular better!
`ApolloClient` can set `defaultOptions` but `create` method can't

**Comment by kamilkisiela** [comment]
`APOLLO_OPTIONS` token and `create` method accept an object of type `ApolloClientOptions`, so `defaultOptions` can be set in both of them. 

Closing but if I'm not true, please @mention me
