### ISSUE TITLE
ERROR in node_modules/apollo-angular/ApolloModule.d.ts

### ISSUE THREAD

**Issue by kosterst** [kamilkisiela/apollo-angular#1525]
**Intended outcome:**
App fails to compile when running npm start.

**Actual outcome:**
Since the compilation failed I am not able to run the app. It ends with this error:

> ERROR in node_modules/apollo-angular/ApolloModule.d.ts: 4: 25 - 
> error TS1149: File name '<dev-path>/node_modules/apollo-angular/selectpipe.d.ts' 
> differs from already included file name '<dev-path>/node_modules/apollo-angular/SelectPipe.d.ts' only in casing.
> 4 import * as ɵngcc1 from './selectpipe';

This is what the ApolloModule.d.ts looks like.
Notice the casing of SelectPipe on lines 2 and 4 differ.

1. import { Apollo } from './Apollo';
2. import { SelectPipe } from './SelectPipe';
3. import * as ɵngcc0 from '@angular/core';
4. import * as ɵngcc1 from './selectpipe';
5. export declare const PROVIDERS: (typeof Apollo)[];
6. export declare const DECLARATIONS: (typeof SelectPipe)[];
7. export declare class ApolloModule {
8.     static ɵmod: ɵngcc0.ɵɵNgModuleDefWithMeta<ApolloModule, [typeof ɵngcc1.SelectPipe], never, [typeof ɵngcc1.SelectPipe]>;
9.     static ɵinj: ɵngcc0.ɵɵInjectorDef<ApolloModule>;
10. }

If I rename line 4 selectpipe to SelectPipe then it compiles with no errors and everything works as expected. But I should not have to do that.

**How to reproduce the issue:**
This is bare bones application with no actual functionality. Using Apollo and GraphQL was the first functionality added.
I am not sure how to reproduce it in stackblitz.

**Versions**
webpack
ts-node: 8.10.2
tslint: 6.1.2
typescript: 3.9.6
angular packages all are version 9+
"apollo-angular": "^1.9.1",
"apollo-angular-link-http": "^1.10.0",
"apollo-cache-inmemory": "^1.6.6",
"apollo-client": "^2.6.10",
"apollo-link": "^1.2.14",
"graphql": "^15.2.0",
"graphql-tag": "^2.10.3",

**Comment by kamilkisiela** [comment]
@kosterst Hi :)

As you can see in https://unpkg.com/browse/apollo-angular@1.9.1/ApolloModule.d.ts, all the imports are correct:

```
import { Apollo } from './Apollo';
import { SelectPipe } from './SelectPipe';
export declare const PROVIDERS: (typeof Apollo)[];
export declare const DECLARATIONS: (typeof SelectPipe)[];
export declare class ApolloModule {
}
```

The `ɵngcc` points to Angular Compiler, so my guess is that NGCC transforms file names and it has nothing to do with Apollo Angular. I could (and will) transform PascalCase file names to param-case just so it won't "confuse" NGCC but you should submit an issue on Angular repo anyway.

**Comment by kamilkisiela** [comment]
[`v1.10.0`](https://github.com/kamilkisiela/apollo-angular/releases/tag/v1.10.0) released
