### ISSUE TITLE
ng serve fails when targeting ES5

### ISSUE THREAD

**Issue by jgomesmv** [kamilkisiela/apollo-angular#1533]
**Intended outcome:**
Successful build 

**Actual outcome:**
Build  failed with the error: Error: Error on worker #3: Error: getInternalNameOfClass() called on a non-ES5 class: expected Apollo to have an inner class declaration

![image](https://user-images.githubusercontent.com/8100887/88919446-02df3800-d263-11ea-82c3-cc657193ecb1.png)

**How to reproduce the issue:**
1 - standard installation of apollo-angular with: **ng add apollo-angular**

2 - setup tsconfig.json with the following config:
"target": "es5",
"lib": ["es2020", "dom"],

3 - run **ng serve** and the compilation fails

**Versions** 
"apollo-angular": "^1.10.0",
"apollo-angular-link-http": "^1.11.0",
"apollo-cache-inmemory": "^1.6.0",
"apollo-client": "^2.6.0",
"apollo-link": "^1.2.11",

**Comment by ValdisThomann** [comment]
Hey mate, which version of angular are you using? I had the same problem in angular 9, but you'll notice that version of apollo-angular-link-http (1.11.0) targets angular 10. Upgrading to angular 10 fixed the build for me.

**Comment by jgomesmv** [comment]
I'm using angular 9.1. So probably that is the cause :)
I was trying to find some info about the versions in the documentation, but with success...
Do you know anything about it?
Thanks for your help!

**Comment by ValdisThomann** [comment]
I was just going off the devDependencies in [apollo-angular-link-http/package.json](https://github.com/kamilkisiela/apollo-angular/blob/master/packages/apollo-angular-link-http/package.json). Angular 10 [drops es5 from the angular package format](https://volosoft.com/blog/what-is-new-in-angular-10), so I just assumed it's related to that.

Angular 10 can still target es5, but it compiles it from es2015. I think maybe if you're using angular 9, but you consume a 3rd party package targeting the Angular 10 package format, that 3rd party package doesn't compile the es5 for you and Angular 9 isn't equipped to target es5 using es2015 package from that 3rd party. Don't quote me on that though, it's just a wild guess.

**Comment by jgomesmv** [comment]
I have tried to install this versions and the problems persists:
    "apollo-angular": "^1.9.1",
    "apollo-angular-link-http": "^1.9.0",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.0",
    "apollo-link": "^1.2.11",

According to npm version history, they were published 4 months ago, by the time version 1.9 was released (it should fully support angular 9):
https://www.npmjs.com/package/apollo-angular
https://www.npmjs.com/package/apollo-angular-link-http
https://www.npmjs.com/package/apollo-cache-inmemory
https://www.npmjs.com/package/apollo-client
https://www.npmjs.com/package/apollo-link

For now as workaround I will target es2015. Angular 10 also supports IE 11 so that's fine for us.
I will need to check a proper configuration of polyfills.
I also didn't found any info about browser support in apollo-angular. That can also be improved.

Thanks for your help!
