### ISSUE TITLE
QueryRef.fetchMore fails to notify valueChanges subscribers.

### ISSUE THREAD

**Issue by marius-klimantavicius** [kamilkisiela/apollo-angular#1545]
Not sure if issue with apollo client or apollo-angular.

Calling `QueryRef.fetchMore` no longer fires `valueChanges`

**To Reproduce**
Create angular 10 project with apollo-angular@2.0.3

```
import { Component, OnInit } from '@angular/core';
import { gql, Apollo, QueryRef } from 'apollo-angular';

// I am using relay style query
const QUERY = gql`
query ...
`;

@Component({
  selector: 'go-reader',
  templateUrl: './go-reader.component.html',
  styleUrls: ['./go-reader.component.scss']
})
export class GoReaderComponent implements OnInit {
  query: QueryRef<any>;
  constructor(private _apollo: Apollo) { }

  ngOnInit(): void {
    this.query = this._apollo.watchQuery<any>({
      query: QUERY,
      variables: {}
    });

    this.query.valueChanges.subscribe(s => console.log(s));
  }

  next() {
    this.query.fetchMore({
      variables: {
        after: 'CURSOR'
      }
    });
  }
}

```

**Expected behavior**

Subscription is fired after `fetchMore` has finished.

**Environment:**

- `@apollo/client`: 3.0.2
- `apollo-angular`: 2.0.3
- `graphql`: ^15.0.0
- `@angular/core`: ~10.0.5
- `@angular/cli`: ~10.0.4
- `typescript`: ~3.9.5

**Additional context**

Disclaimer: I don't have too much experience with angular, apollo or rxjs just was assigned a project a few days ago. 
My initial version was using apollo-angular 1.0.x and it was correctly firing in response of `fetchMore`. I've updated to apollo-angular 2.0.3 (mostly by recreating my project and just copying the components) and `fetchMore` stopped working (note that promise returned by `fetchMore` fires correctly after retrieving data, I was planning to use this as workaround but the issue with using the data directly is that client fields are not there yet[?]).

**Comment by marius-klimantavicius** [comment]
Tried setting fetch policy (both initial fetch and next fetch) to `cache-and-network` (and used `updateQuery` to simply return the next fetch result) - this caused `valueChanges` to fire, however the result was stale.

**Comment by kamilkisiela** [comment]
@marius-klimantavicius `fetchMore` needs `updateQuery` to be defined, here is the pagination chapter for [v1](https://apollo-angular.com/docs/1.0/recipes/pagination) and [v2](https://apollo-angular.com/docs/data/pagination).

`refetch` is to fetch data again but either with different variables or different fetch policy, it's to update query's data.
`fetchMore` is to fetch more data - useful for pagination

**Comment by kamilkisiela** [comment]
I checked both of them and they work perfectly. If you're still seeing an issue, please @mention me here.

**Comment by marius-klimantavicius** [comment]
There was no issue in v1 when I implemented it.
My initial code tried using `updateQuery`, however v2 displays a warning that it is not recommended (I tried both with and without `updateQuery`). The problem I encountered at that time was that when I requested second page I'd get `valueChanges` to fire however I would either only get the first page again (in devtools I could even see multiple requests, one for first page another for second) or type resolvers (I needed `@client` field) would not run.

I've switched to doing manual requests for now but I'll try to reproduce my scenario when/if I have some spare time.

**Comment by marius-klimantavicius** [comment]
Just tried reproducing - it did work correctly. Maybe later will try to go back to revision that was not working and try it again.

**Comment by RollsChris** [comment]
Hi, I'm using  "apollo-angular": "^8.0.0", there is no updateQuery function on the fetchMore function anymore: 

![Image](https://github.com/user-attachments/assets/7ee29057-3cbe-42f0-859f-47014a346f84) what am i missing? when i call fetchMore its not firing the value Changes.

Complete Code: 

![Image](https://github.com/user-attachments/assets/85830dd5-0bc5-407c-b885-3182b6e6248b)

Thanks
