### ISSUE TITLE
No support for Nx workspace in ng add 

### ISSUE THREAD

**Issue by vladimirdrayling** [kamilkisiela/apollo-angular#1547]
**Bug description**

Failed to execute the following command `nx add apollo-angular`.
Output:
```
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
? Url to your GraphQL endpoint some-endpoint-url
Couldn't read tsconfig.json!
```

**Steps to reproduce the behavior:**

* `npx create-nx-workspace some-workspace --style=scss --preset=angular --cli=angular --nx-cloud=false`
* `nx add apollo-angular`

**Expected behavior**

Graphql module should be created.

**[Repo](https://github.com/vladimirdrayling/nx-apollo-angular)**

**Comment by LMFinney** [comment]
The problem is that nx10 changed `tsconfig.json` to `tsconfig.base.json`.

Workaround:

1. Rename `tsconfig.base.json` to `tsconfig.json`
2. Run `nx add apollo-angular`
3. Rename `tsconfig.json` back to `tsconfig.base.json`

**Comment by vladimirdrayling** [comment]
Is there an adjustment for `tsconfig.base.json` in the future releases, so we don't need to rename back and forth?

**Comment by LMFinney** [comment]
I don't know a lot about the change from `tsconfig.json` to `tsconfig.base.json`. Here's some discussion about it by Victor Savkin from Nrwl: https://twitter.com/victorsavkin/status/1292930105896046593

**Comment by g-joshi** [comment]
Just create a tsconfig.json next to tsconfig.base.json and extend from tsconfig.base.json. Problem solved!!!!

// tsconfig.json
{
  "extends": "./tsconfig.base.json"
}
