### ISSUE TITLE
Docstring of ApolloTestingController expectOne is missing something

### ISSUE THREAD

**Issue by Cito** [kamilkisiela/apollo-angular#1571]
The [docstring of expectOne](https://github.com/kamilkisiela/apollo-angular/blob/e25d4f8dae63ec1a1b7d9e03279e4e79639c7841/packages/apollo-angular/testing/src/controller.ts#L25) says 

```
   /**
     * Expect that a single  has been made which matches the given URL, and return its
     * mock.
     *
     * If no such  has been made, or more than one such  has been made, fail with an
     * error message including the given  description, if any.
     */
```

Obviously a word (probably "operation") is missing after "single" and after "such".

Note that the same problem exists in several other places.

**Comment by kamilkisiela** [comment]
Fixed
