### ISSUE TITLE
watchQuery over-fetching

### ISSUE THREAD

**Issue by klemenoslaj** [kamilkisiela/apollo-angular#1573]
**Describe the bug**

When there are multiple watch-queries active on the same page it often happens that they all send a new network request.

For an example, having active one watchQuery on the page and activating another one from deeper in the components tree will trigger the request for both queries.

**Example**

1st query

```
query {
  file(id: 1000) {
    id
    name
    size
  }
}
```

2nd query

```
query {
  file(id: 1000) {
    id
    name
    mimetype
  }
}
```

When 2nd query is executed, the 1st query is sending a new network request again effectively over-fetching.

**To Reproduce**

Reproduction: https://stackblitz.com/edit/simple-apollo-angular-example-maz5cx
Keep refreshing with stackblitz refresh button and more often than not (gif bellow).

**Expected behavior**

The 1st query should not be triggered together with 2nd query. If any field shared between the two queries changes with response of 2nd query, the 1st watchQuery should update due to cache changes anyway.

**Environment:**

- `@apollo/client`: 3.2.1
- `apollo-angular`: 2.0.4
- `graphql`: 15.3.0
- `@angular/core`: 10.1.3
- `@angular/cli`: 10.1.3
- `typescript`: 4.0.3

**Additional context**

![apollo-over-fetching](https://user-images.githubusercontent.com/7548247/94655303-a77f0400-02fe-11eb-902c-9e8fc40af303.gif)

**Comment by kamilkisiela** [comment]
That's Apollo Client related, Apollo Angular is just an integration laye, please submit an issue [here](https://github.com/apollographql/apollo-client/issues/new/choose)

**Comment by klemenoslaj** [comment]
Done: https://github.com/apollographql/apollo-client/issues/7114

**Comment by kamilkisiela** [comment]
Thank you :) I hope Apollo will fix it
