### ISSUE TITLE
Multiple errors in ng add apollo-angular

### ISSUE THREAD

**Issue by adammfrank** [kamilkisiela/apollo-angular#1574]
**Describe the bug**

I'm trying to add apollo-angular to an existing Angular 9 project.
When I first run the command I get the error "Couldn't read tsconfig.base.json!"
After adding an empty tsconfig.base.json, I get the errors
> We couln't enable 'allowSyntheticDefaultImports' flag.
It's required by '@apollo/client/core' package so please add it to your tsconfig.

> Cannot read property 'kind' of undefined

I already had allowSyntheticDefaultImports turned on. When I remove it that error goes away but
> Cannot read property 'kind' of undefined

remains and prevents me from installing apollo-angular

**To Reproduce**

`npx ng add apollo-angular`

**Expected behavior**
Apollo-angular gets added

**Environment:**

- `@apollo/client`: None
- `apollo-angular`: None
- `graphql`: None
- `@angular/core`: 9.1.1
- `@angular/cli`: 9.1.1
- `typescript`: 3.7.5

**Additional context**

**Comment by DustinJSilk** [comment]
Having this same issue, can't instally and can't figure out why so far. Managed to fix the first issues with allowSyntheticDefaultImports though.

Im running angular as a nestjs monorepo app

**Comment by awaism551** [comment]
I was also facing multiple errors while adding `apollo-angular` to project, it was due to some ts configuration issues this change in `lib`  array in tsconfig.json worked for me, my angular version was 9
`"lib": ["es6", "dom", "esnext", "esnext.asynciterable"],`

**Comment by PlastMan420** [comment]
Hello, this is an old issue but I got it recently. it appeared in my case because that that option was already present in my tsconfig.json. deleting that line will let it proceed normally. and it will be added back by the cli tool.
I'm running Angular 15.1 + Apollo-angular 4.2
