### ISSUE TITLE
ApolloModule doesn't exists in package apollo-angular

### ISSUE THREAD

**Issue by JacopoSciampi** [kamilkisiela/apollo-angular#1576]
**Describe the bug**

Following the starting guide or the migration one it shows that we need to use ApolloModule. By copying the code it shows off that ApolloModule doesn't exists in that package. This error won't let  me upgrade my current code that works fine usuing the 1.x version of apollo-angular.

**To Reproduce**

Just follow the guide

**Expected behavior**

I think that the import should be fine w/o errors

**Environment:**

- `@apollo/client`: 3..2.4
- `apollo-angular`: 2.0.4
- `graphql`: 15.3.0
- `@angular/core`: 10.1.6
- `@angular/cli`: 10.1.7
- `typescript`: 4.0.3

**Additional context**

**Comment by fetis** [comment]
@JacopoSciampi `ApolloModule` was dropped from version 2. Where do you see it the migraiton guide?

**Comment by montechie** [comment]
I think the confusion (which caught me up as well) is between the setup docs for angular-apollo at apollographql.com which still include ApolloModule and apollo-angular.com. Apollographql.com is going to be the reference that is more prominent when searching for adding Apollo + Graphql + Angular.

**Comment by fetis** [comment]
@montechie Angular guide was moved to `appollo-angular`, atm you can't even select it from the menu on `apollographql`, but you're right it's still available by direct link with search.

@kamilkisiela how do you think, will it be possible to set up redirects for the new site?

**Comment by fetis** [comment]
@JacopoSciampi I would like to close this issue because there's nothing to do here

For documentation redirect there's #1587
