### ISSUE TITLE
Schematic update re-orders imports

### ISSUE THREAD

**Issue by fetis** [kamilkisiela/apollo-angular#1577]
Probably not a that important, but annoying to redo on all files.

My code before migration
```
import { Injectable } from '@angular/core';
import { Apollo } from 'apollo-angular';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
```

My code after migration
```
import {Apollo} from 'apollo-angular';
import { Injectable } from '@angular/core';

import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
```

So Apollo import was just lifted up. 

**Environment:**

- `apollo-angular`: 2.0.4

**Comment by kamilkisiela** [comment]
Yeah, the update script collects imported/exported identifiers and recreate import statements. I'm open for a pull request adjusting it a bit.
