### ISSUE TITLE
ApolloQueryResult<unknown>>' is missing the following properties from type 'Observable<any>'

### ISSUE THREAD

**Issue by krejko** [kamilkisiela/apollo-angular#1579]
**Describe the bug**

I was following the instructions on the repo's homepage: https://github.com/kamilkisiela/apollo-angular

`dogs: Observable<any>;`

`ngOnInit() {`
`      this.dogs = this.apollo`
`            .watchQuery({`
`                 query: GET_DOGS,`
`             })`
`            .valueChanges.pipe(map(result => result.data && result.data.dogs));`
`}`

However, when I try to assign the `this.dogs` I get the following error: 
`Type 'Observable<ApolloQueryResult<unknown>>' is missing the following properties from type 'Observable<any>': [Symbol.observable], map, filter, reduce, and 2 more.ts(2740)`

I also get a typescript error on `result.data.dogs`:
`Property 'dogs' does not exist on type 'unknown'.`

**To Reproduce**
Follow the instructions on the page listed above to observe that you cannot assign the observable. 

**Expected behavior**

I expected following the instructions exactly would not generate an error. 

**Environment:**

- apollo-client "^2.6.10"
- apollo-angular "^2.0.4"
- Angular 10

**Additional context**

None at the moment.

**Comment by KeithGillette** [comment]
`apollo-angular@^2.0.0` is meant for use with `@apollo/client@^3.0.0`, not `apollo-client`.

**Comment by krejko** [comment]
Hi @KeithGillette, I had installed the `apollo-angular` using the `ng add apollo-angular` as indicated in the instructions. These were the dependencies. If this is indeed the issue, this this ticket should be to update what dependencies comes with the `ng  add` command.

**Comment by ntziolis** [comment]
@kamilkisiela There is still an issue regarding this:
- When calling an apollo angular service `myService.watch(variables)` the return type is an rxjs observable
- Now I want assign the return value to a variable in the class I would write `values: Observable<ApolloQueryResult<MyQuery>>`
- Usually at this point typescript would complain that Observable is unknown and I need to import it, which I would usually do via vscode auto import
- However `Observable` is already defined globally in the apollo client package: `https://github.com/apollographql/apollo-client/blob/main/src/utilities/observables/Observable.ts`
- The result is the error `Property '['@@observable']' is missing in type import("/node_modules/rxjs/internal/Observable")`

There are two solutions we know of currently:
- Manually import Observable every time an apollo angular service is used, which is everywhere.
- Monkey patch the observable file form the apollo client via patch-package:
```
import Observable from 'zen-observable';
import 'symbol-observable';
export declare type ObservableSubscription = ZenObservable.Subscription;
export declare type Observer<T> = ZenObservable.Observer<T>;
export declare type Subscriber<T> = ZenObservable.Subscriber<T>;
declare global {
    interface Observable<T> {
        // we simply removed the line below
        // it might have necessary for older rxjs versions but does not seem to be anymore
        //['@@observable'](): Observable<T>;
    }
}
export { Observable };
//# sourceMappingURL=Observable.d.ts.map
```

Is there any known proper solution to this issue?

Our rxjs version is >6.6.3.
