### ISSUE TITLE
When using notifyOnNetworkStatusChange=true and useInitialLoading=true, observable is called twice with loading=true

### ISSUE THREAD

**Issue by cjohn001** [kamilkisiela/apollo-angular#1584]
**Describe the bug**

When using notifyOnNetworkStatusChange=true and useInitialLoading=true to display the loading state of a watch and fetchmore query, the observable is always called three times. The first two times with loading=true and the third time with loading= false. This is the same for fetchPolicy cache-first and network-only (I only tried these policies)
 
**To Reproduce**
```
                this._queryResultQueryRef = this.diaryEntriesSrv.watch(
			{ intervalFrom: this._intervalFrom, intervalTo: this._intervalTo },
			{
				notifyOnNetworkStatusChange: false,
				useInitialLoading: true,
				fetchPolicy: 'cache-first' // FIXME
			}
		);

		// when initialized the service is triggered two times with loading= true, 
		this._queryResult$ = this._queryResultQueryRef.valueChanges;
		this._querySubscription = this._queryResult$.subscribe(({ data, loading }) => {
			console.log('loading = ' + loading);
			if (loading) {
				this.loadingOverlaySrv.requestStarted();
			} else {
				this.loadingOverlaySrv.requestFinished();
			}
		});

```
**Expected behavior**
Observable is called only two times. First time with loading=true and second time with loading= false

**Environment:**

"@apollo/client": "~3.2.5",
"apollo-angular": "~2.0.4",
"graphql": "^15.3.0",
"@angular/core": "~10.1.6",
-"@angular/cli": "~10.1.7",
"@angular/compiler-cli": "~10.1.6",
"typescript": "~3.9.2"

Further comment:
It would be nice if the documentation would be enriched by an example which shows how loading state is meant to be used. It seems like if I use fetchMore on the above query, in case of new data received the observable is triggered once with loading state false, whereas when no new data are fetch it is not called. I only want to show a simple spinner as long as an load or fetchMore operation is in place. I would expect to get the observable called one with loading=true and once with loading=false. However, the loading state seems to be totally messed up for me. Hence, a usage example in the docs would be great.

**Comment by kamilkisiela** [comment]
Fix for `useInitialLoading: true` is on `master` branch already, I will comment here again once it's released.

**Comment by cjohn001** [comment]
Hello @kamilkisiela , I was wondering if the bugfix was included in "apollo-angular": "2.1.0". I ask because I think I am observing a different behavior now. 
Now, I correctly see 2 calls to the function with 1. loading=true and 2. loading=false when the data are not in the cache. However, when data is already persisted in the cache, I also get to function calls, two times with loading=false. Should I add a different issue for it?

**Comment by kamilkisiela** [comment]
@cjohn001 no but could you create a small reproduction or even better, a test in this repo?

**Comment by cjohn001** [comment]
Hello @kamilkisiela,
I am unfortunately not understanding how the tests here are written and I am not sure if I understand correctly how the API of apollo angular is to be used by means of how  notifyOnNetworkStatusChange and useInitialLoading are working together. All permutations of the two parameters do not seem to lead to a reasonable result. 

I am trying to show a loading spinner when data are loaded via network, if loaded from cache no loading spinner should appear
 
I am using the service interface

service.watch({  },{ notifyOnNetworkStatusChange: true, useInitialLoading: true, fetchPolicy: 'cache-first'
}).valueChanges.subscribe( ({ data, loading }) => {} )

What I would expect with this configuration is

A ) If data is not in the cache the callback should be called twice 1. loading = true, 2. loading = false + data set
B ) If data is in the cache the callback should be called once with loading = false, + data set


1. Is my assumption right that  notifyOnNetworkStatusChange: true and  useInitialLoading: true  should lead to this behavior or is my assumption wrong?

2. Why do I need two flags here to control if loading state is shown or not. This seems weird to me. What is notifyOnNetworkStatusChange and useInitialLoading is meant to be used for. From the behavior I do not get a clue.

**Comment by kamilkisiela** [comment]
v3 should fix it
