### ISSUE TITLE
Export persisted-queries is not available in apollo-angular 2.0.4

### ISSUE THREAD

**Issue by havran** [kamilkisiela/apollo-angular#1588]
**Describe the bug**

I use lastest version 2.0.4.
I try use persited queries as is described in documentation here:

https://apollo-angular.com/docs/recipes/automatic-persisted-queries

or:

https://github.com/kamilkisiela/apollo-angular/blob/86af0c1a2556f38d80a5c90941aee933baee6c0c/website/docs/recipes/automatic-persisted-queries.md

Seems like export for persisted queries is not available `import { createPersistedQueryLink } from 'apollo-angular/persisted-queries';`

**Environment:**

- `@apollo/client`: 3.2.5
- `apollo-angular`: 2.0.4
- `graphql`: 14.7.0
- `@angular/core`: 10.1.4
- `@angular/cli`: 10.1.4
- `typescript`: 4.0.3

**Comment by havran** [comment]
I found my problem - i expect that latest 2.0.4 version already includes changes related to persisted queries, but not. I build latest library version locally and linked it in my project and now all works like is described in documentation.

Then i have only one question. When is next release planed?

Thanks for great work, this helps me a lot to understand, how Apollo client work 👍 .

**Comment by muuvmuuv** [comment]
Please re-open it is not resolved because IT IS NOT included.

**Comment by havran** [comment]
As requested, issue is reopened.

**Comment by kamilkisiela** [comment]
[`v2.1.0`](https://github.com/kamilkisiela/apollo-angular/releases/tag/v2.1.0)

**Comment by yringler** [comment]
Hmm...
@kamilkisiela, I can only [get this working ](https://github.com/Health-Freedom/site/tree/master/client) if I use the default createhttplink, not with angular apollos link.
thoughts?

```javascript
const uri = 'https://strapi.yrtestingdomainfor.info/graphql';

export function createApollo(httpLink: HttpLink): ApolloClientOptions<any> {
  const link = ApolloLink.from([
    createPersistedQueryLink({ useGETForHashedQueries: true }) as any,
    createHttpLink({ uri })
  ]);

  const persisted = createPersistedQueryLink();
  const http = httpLink.create({
    uri,
  });

  const angularLink = persisted.concat(http);

  return {
    // This gets me posts, using the link variable uses get
    link: angularLink,
    cache: new InMemoryCache(),
    defaultOptions: {
      watchQuery: {
        notifyOnNetworkStatusChange: true
      }
    }
  };
}
```
