### ISSUE TITLE
Client name and version not sent through http headers

### ISSUE THREAD

**Issue by mmeylan** [kamilkisiela/apollo-angular#1591]
**Describe the bug**

According to [the documentation](https://www.apollographql.com/docs/studio/client-awareness/), setting the `name` and `version` fields in the constructor will automatically populate `apollographql-client-name` and `apollographql-client-version` headers so that apollo server can have client information when reporting metrics about the schema usage. 

Setting `name` and `version` does not populate the headers and one has to manually set them.

```typescript
{
      provide: APOLLO_OPTIONS,
      deps: [HttpLink],
      useFactory: (httpLink: HttpLink): ApolloClientOptions<any> => {
        return {
          cache: new InMemoryCache(),
          // these don't seem to work, hence the explicit headers below
          name: 'my-client-name',
          version: 'my-client-version,
          link: httpLink.create({
            uri: apiUrl,
            // this works
            headers: new HttpHeaders({
              'apollographql-client-name': 'my-client-name',
              'apollographql-client-version': 'my-client-version',
            }),
          }),
        }
      },
},
```

**Expected behavior**

 `apollographql-client-name` and `apollographql-client-version` should be set when `name` and `version` are present in the client constructor argument.

**Environment:**

- `@apollo/client`: 3.2.5
- `apollo-angular`: 2.0.4
- `graphql`: 15.4.0
- `@angular/core`: 10.1.2
- `@angular/cli`: 10.1.2
- `typescript`: 4.0.2

**Comment by fetis** [comment]
at first glance, it should work. options passed to `ApolloClient` constructor directly with any changes.
@mmeylan how do you create your instance? I see only options provider.

**Comment by kamilkisiela** [comment]
#1592 :)

**Comment by kamilkisiela** [comment]
[`v2.1.0`](https://github.com/kamilkisiela/apollo-angular/releases/tag/v2.1.0)
