### ISSUE TITLE
ApolloTestingController doesn't flush fragments anymore ?

### ISSUE THREAD

**Issue by Niid** [kamilkisiela/apollo-angular#1593]
**Describe the bug**

After upgrading from apollo-angular 1.9.x to 2.0.4, an existing Jest unit test stopped working. We expect some arguments contained in a fragment, yet the request flush gives everything as expected except the fragment. Am I doing something wrong or is that a real bug ?

**To Reproduce**
Declare a GraphQL query with a fragment (should look something like that in a graphql.ts file):
```
export const FRAGMENT: string = `fragment SomeFragment on FragmentedItem {
    fragmentItem{
        id
    }
}`;

export const QUERY: DocumentNode = gql `query{
    anItem{
        aFragmentedItemOfTypeFragmentedItem{
            ... SomeFragment
            someOtherProperty
        }
    }
}`
```

Set up a jest test that contains a flush looking like so:
```
it('should give a full object', () => {
    const { controller } = getFixtures();
        controller.expectOne(QUERY).flush({
            data: {
                anItem: {
                   aFragmentedItemOfTypeFragmentedItem:{
                       id: 1
                       someOtherProperty: 2
                   }
                }
            }
      });
```

The result of the flush will not include id.

**Expected behavior**

The result of the flush should includethe fragmented property "id"

**Environment:**

- `@apollo/client`:3.0.0
- `apollo-angular`:2.0.4
- `graphql`:15.0.0
- `@angular/core`:10.1.5
- `@angular/cli`:10.1.5
- `typescript`:3.9.7

**Comment by fetis** [comment]
I managed to reproduce it locally.

You need to specify a `__typename` field for an object that will be used to fulfill fragment fields. So, for your example, it will be
```
aFragmentedItemOfTypeFragmentedItem:{
    __typename: 'FragmentedItem'
    id: 1
    someOtherProperty: 2
}
```

I believe it's connected to [breaking changes in InMemoryCache](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#inmemorycache) and drop of `FragmentMatcher`

**Comment by Niid** [comment]
Hello ! 
Sorry for the response time, I tried it and indeed it works great now.
Thanks for the help !
