### ISSUE TITLE
Which angular versions are supported? (v8,v9,v10 etc)

### ISSUE THREAD

**Issue by benwinding** [kamilkisiela/apollo-angular#1597]
**Describe the bug**
- I can't seem to find any information about which @angular versions that this library supports? 7,8,9,10 ect.
- We have an angular 8 project, this package throws a many errors due to angular 8 requiring older versions of typescript (which we cannot change due to the angular compiler throwing errors)

This should probably added to the documentation, as most people would love to add this to existing angular projects, and it's not always trivial to upgrade a large application to the latest version of angular...

**Comment by UchihaYuki** [comment]
Hi, I just got the answer from @dotansimha:
> v2 of apollo-angular works with Angular 10 and Apollo Client v3
But as specified in [issue 7335](https://github.com/apollographql/apollo-client/issues/7335), you might have to use @apollo/client@3.2.5 temporarily, until the bug is fixed. (At least I think it's a bug, haven't spent time on it though)

**Comment by dotansimha** [comment]
And if you are using Apollo-Client v2, please use `apollo-angular@v1` and make sure to update the latest. (v1.10 supports Angular 10, see the release notes: https://github.com/kamilkisiela/apollo-angular/releases/tag/v1.10.0)

**Comment by dotansimha** [comment]
PR to update the docs: https://github.com/kamilkisiela/apollo-angular/pull/1598
