### ISSUE TITLE
Hard to debug compile errors when using the wrong import for the `gql` tag

### ISSUE THREAD

**Issue by roschlau** [kamilkisiela/apollo-angular#1601]
In my Angular project, if I accidentally `import { gql } from '@apollo/client'` instead of `import { gql } from 'apollo-angular'`, I get the following errors when compiling the project:

```
ERROR in ./node_modules/@apollo/client/react/context/ApolloConsumer.js
Module not found: Error: Can't resolve 'react' in 'C:\source\echometer\frontend\node_modules\@apollo\client\react\context'

ERROR in ./node_modules/@apollo/client/react/context/ApolloProvider.js
Module not found: Error: Can't resolve 'react' in 'C:\source\echometer\frontend\node_modules\@apollo\client\react\context'

ERROR in ./node_modules/@apollo/client/react/context/ApolloContext.js
Module not found: Error: Can't resolve 'react' in 'C:\source\echometer\frontend\node_modules\@apollo\client\react\context'

ERROR in ./node_modules/@apollo/client/react/hooks/useApolloClient.js
Module not found: Error: Can't resolve 'react' in 'C:\source\echometer\frontend\node_modules\@apollo\client\react\hooks'

ERROR in ./node_modules/@apollo/client/react/hooks/useReactiveVar.js
Module not found: Error: Can't resolve 'react' in 'C:\source\echometer\frontend\node_modules\@apollo\client\react\hooks'

ERROR in ./node_modules/@apollo/client/react/hooks/useSubscription.js
Module not found: Error: Can't resolve 'react' in 'C:\source\echometer\frontend\node_modules\@apollo\client\react\hooks'

ERROR in ./node_modules/@apollo/client/react/hooks/useMutation.js
Module not found: Error: Can't resolve 'react' in 'C:\source\echometer\frontend\node_modules\@apollo\client\react\hooks'

ERROR in ./node_modules/@apollo/client/react/hooks/utils/useBaseQuery.js
Module not found: Error: Can't resolve 'react' in 'C:\source\echometer\frontend\node_modules\@apollo\client\react\hooks\utils'

ERROR in ./node_modules/@apollo/client/react/hooks/utils/useDeepMemo.js
Module not found: Error: Can't resolve 'react' in 'C:\source\echometer\frontend\node_modules\@apollo\client\react\hooks\utils'
```

It would be nice to at least have some way to pinpoint the error in this case - took me a good while of trial and error until I found the culprit. I've added an `import-blacklist` entry for the offending import in my tslint.json, but that only becomes an option once you know about the actual problem, and might not be an option for others at all.

**Environment:**

- `@apollo/client`: `3.0.0`
- `apollo-angular`: `^2.0.4`
- `graphql`: `^15.0.0`
- `@angular/core`: `~10.2.0`
- `@angular/cli`: `~10.2.0`
- `typescript`: `~4.0.2`

**Comment by fetis** [comment]
I experienced the same issue recently, but I have no idea how it can be solved on the library level.

**Comment by nthornton2010** [comment]
The only way this library would be able to do anything about it is by renaming it's version of gql to something different so that the compiler doesn't suggest multiple choices. I'd say the real issue is with the @apollo library for not separating their code base into react and angular directories.

It's annoying but something that I think all apollo devs outside of react are forced to live with.

At the end of the day, I don't think this is the responsibility of this library.

**Comment by marcus-sa** [comment]
Some IDE's and linters can blacklist imports, so that it won't suggest them.

**Comment by fetis** [comment]
There's nothing to do from our side. If someone will come up with an idea of how to prevent this, let's us know. For now, I close it.
