### ISSUE TITLE
cache.write warnings "Cache data may be lost" cannot be suppressed

### ISSUE THREAD

**Issue by Cito** [kamilkisiela/apollo-angular#1617]
I got the warning message mentioned in apollographql/apollo-client#6451:

    Cache data may be lost when replacing the notifications field of a Query object.

Tp suppress the message I followed the advice given in the same issue  apollographql/apollo-client#6451, using `cache.evict` and `cache.modify`. However,  the `cache.modify` options do not seem to have the `notifications` property in apollo-angular. And the warning still appeared, when I forced it to use it anyway. Both methods `cache.evict` and `cache.modify` did not work for me.

- `@apollo/client`: 3.3.6
- `apollo-angular`: 2.1.0
- `graphql`: 15.4.0

**Comment by kamilkisiela** [comment]
There is no `notifications` options, it's the name of the field from a query: `Query.notifications`. Closing, it's related to Apollo Client.
