### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by paliwalgaurav** [kamilkisiela/apollo-angular#1618]
**Describe the bug**

`ERROR in node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.d.ts:7:87 - error TS1144: '{' or ';' expected.

7 export declare function invariant(condition: any, message?: string | number): asserts condition;
                                                                                        ~~~~~~~~~
`

**To Reproduce**
- install apollo-angular@2.x.x
- run the configured project

**Expected behavior**
- should compile without any internal library issue

**Environment:**

- `@apollo/client`:
- `apollo-angular`:
- `graphql`:
- `@angular/core`:
- `@angular/cli`:
- `typescript`:

**Comment by paliwalgaurav** [comment]
upgrading `typescript` to `>3.7` can resolve the problem

**Comment by sw-dev-code** [comment]
@paliwalgaurav You should state this somewhere in documentation because it limits the Angular version. For example, because of this, I can't use it in my Angular v8 project.
