### ISSUE TITLE
Documentation on cache persistance not clear enough

### ISSUE THREAD

**Issue by ToledoNicola** [kamilkisiela/apollo-angular#1621]
**Describe the bug**
https://github.com/kamilkisiela/apollo-angular/blob/master/website/docs/caching/advanced-topics.md#cache-persistence

the documentation is not clear enough as it is not clear how to implement persistence with the apollo-angular configuration with the APOLLO_OPTIONS token

**To Reproduce**

**Expected behavior**
have more examples using the token APOLLO_OPTIONS

**Environment:**

- `@apollo/client`:
- `apollo-angular`:
- `graphql`:
- `@angular/core`:
- `@angular/cli`:
- `typescript`:

**Additional context**

**Comment by muuvmuuv** [comment]
I am also interested in this. My idea was to have an async `APOLLO_NAMED_OPTIONS` provider but Angular does not allow async providers.

```ts
@NgModule({
  providers: [
    PVTECService,
    {
      provide: APOLLO_NAMED_OPTIONS,
      useFactory(
        middleware: MiddlewareService,
        configService: AppConfigService
      ): NamedOptions {
        const uri = "uri url"
        return middleware.createService('PVTEC', '0.0.0', uri)
      },
      deps: [MiddlewareService, AppConfigService],
    },
  ],
})
export class FraunhoferPVTECGateServiceModule {}
```

```ts
  createService(
    name: string,
    version: string,
    uri: URILink,
    options?: DefaultOptions
  ): NamedOptions {
    const link = this.getLink(uri)
    options = this.createOptions(options)

    const slug = stringToSlug(name)
    console.info(`Registered Apollo service "${name}" with slug "${slug}"`)

    const cache = new InMemoryCache({})

    // THIS SEEMS TO NOT WORK
    persistCache({
      cache,
      storage: new LocalStorageWrapper(window.localStorage),
    })

    return {
      [slug]: {
        name: name,
        version: version,
        link: link,
        defaultOptions: options,
        cache: cache,
      },
    }
  }
```

**Comment by muuvmuuv** [comment]
Any updates on this? Tried to fiddling around by creating a `APP_INITIALIZER` but this also seems to not work as expected.

**Comment by kamilkisiela** [comment]
It's now described in docs https://github.com/kamilkisiela/apollo-angular/blob/master/website/docs/caching/advanced-topics.md#cache-persistence
