### ISSUE TITLE
Allow zone.js peer dependency ~0.11.0

### ISSUE THREAD

**Issue by qortex** [kamilkisiela/apollo-angular#1623]
With Angular 11.1.0 switch to new `zone.js` version 0.11.3, `apollo-angular` prevents my project from updating zone:
```
Package "apollo-angular" has an incompatible peer dependency to "zone.js" (requires "~0.8.20 || ~0.9.0 || ~0.10.0", would install "0.11.3").
```

I suspect `apollo-angular` is compatible with `zone.js` new version, so it should be immediate to unpin the version and allow 0.11.3?

Note: I forced the update in my project and it works fine.

**Comment by wesselvdv** [comment]
This is also causing issues for people using npm v7.

**Comment by fetis** [comment]
@kamilkisiela I've made all changes could you plz release it?

**Comment by sasidhar** [comment]
@kamilkisiela Could you please release it?

**Comment by kamilkisiela** [comment]
`v2.3.0` :)
