### ISSUE TITLE
After migration to v2 - Comma from query can be removed

### ISSUE THREAD

**Issue by dlarr** [kamilkisiela/apollo-angular#1631]
**Describe the bug**

I am try to migrate from v1.10.0 to v2.2.0
I used the ng update apollo-angular schematics and things went pretty well.

Problem is with some request the resulting query within request payload removed sont comma that are mandatory for execution

Here is the request written in my code (some filters and field are parameters here)
The interesting line is 
**dateHistogram(period: "7d", metricAggregation: "max", timestampField: "timestamp") {** 

```
return gql(`
    query QualityHistoryRequest($project: String, $from: String) {
    dateHistogram(period: "7d", metricAggregation: "max", timestampField: "timestamp") {
      qualityAnalyses(
        filter: {
          op: AND
          criteria: [
            ${getFilters(context)}
            { field: "timestamp", comparator: GREATER_THAN, value: $from }
          ]
        }
      ) {
        timestamp
        measures {
           ${getMeasure(widgetConfig)}
        }
      }
    }
  }
```

The problem is that when the HTTP request is actually posted the commas are removed and replaced by a carriage return 

![image](https://user-images.githubusercontent.com/2865021/107532854-9d2f1980-6bbe-11eb-917c-1a7b88392160.png)

In a copy/paste here is the result:

```
"query QualityHistoryRequest($project: String, $from: String) {
  dateHistogram(
    period: "7d"
    metricAggregation: "max"
    timestampField: "timestamp"
  ) {
    qualityAnalyses(
      filter: {op: AND, criteria: [{field: "projectId", comparator: MATCH, value: "something(:.*)?"}, {field: "branch", comparator: MATCH, value: "develop(/.*)?"}, {field: "timestamp", comparator: GREATER_THAN, value: $from}]}
    ) {
      timestamp
      measures {
        critical_violations
        blocker_violations
        major_violations
        minor_violations
        info_violations
        __typename
      }
      __typename
    }
    __typename
  }
}
"
```

See how commas have been removed ?

**To Reproduce**
Steps to reproduce the behavior: I don't know

**Expected behavior**

These commas need to be kept

**Environment:**

- `@apollo/client`: ^3.0.0
- `apollo-angular`: ^2.2.0
- `graphql`: ^15.0.0
- `@angular/core`: ^10.0.6
- `@angular/cli`: ^10.0.4
- `typescript`: 3.9.7

**Additional context**

The problem may come from Apollo/Client but I can't find an answer talking about these commas replacement

**Comment by dlarr** [comment]
waw it's kinda dead around here :(

**Comment by fetis** [comment]
we're not dead, but slow :)

**Comment by kamilkisiela** [comment]
https://github.com/kamilkisiela/apollo-angular/pull/1642/commits/f6902f24082f4100baedafcdea01e703c7025522
it's totally fine and correct when it comes to graphql spec. We introduced [`operationPrinter `](https://github.com/kamilkisiela/apollo-angular/blob/master/packages/apollo-angular/CHANGELOG.md#v240) option to write your own printing logic or even use `stripIgnoredCharacters` of graphql.
