### ISSUE TITLE
Can not test correctly with jest

### ISSUE THREAD

**Issue by tso1158687** [kamilkisiela/apollo-angular#1636]
**Describe the bug**
the testing inside the graphql subscribe function would pass directly and not execute by using jest.
if using karma (angular default testing package), it would be correct

**To Reproduce**
here is my testing code copy from official [doc](https://apollo-angular.com/docs/development-and-testing/testing)

```
import {
  ApolloTestingModule,
  ApolloTestingController,
} from 'apollo-angular/testing';
import { TestBed } from '@angular/core/testing';

import { GraphqlService, GRAPHQL_QUERY } from './graphql.service';
import { Apollo } from 'apollo-angular';

describe('GraphqlService', () => {
  let controller: ApolloTestingController;
  let service: GraphqlService;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [ApolloTestingModule],
    });

    service = TestBed.inject(GraphqlService);
    controller = TestBed.inject(ApolloTestingController);
  });

  afterEach(() => {
    controller.verify();
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  // HERE IS THE PROBLEM WHERE IT IS
 // this test should be FAILED but passed
  it('should get data from graphql', () => {
    service.getData().subscribe((data) => {
      console.log('1')
      expect(false).toBeTruthy()
      console.log('2')
      expect(1).toBe(2)
      console.log('3')
    });
    
    // copy from apollo-angular doc
    // https://apollo-angular.com/docs/development-and-testing/testing
    const op = controller.expectOne(GRAPHQL_QUERY);
    op.flush({
      data: {
        dog: {
          id: 0,
          name: 'Mr Apollo',
          breed: 'foo',
        },
      },
    });
    controller.verify();
  });
});
```

**Expected behavior**
it should be failed but passed
```
service.getData().subscribe((data) => {
      console.log('1')
      expect(false).toBeTruthy()
      console.log('2')
      expect(1).toBe(2)
      console.log('3')
    });
```
I look into this code, it simply print `1`, not `2` and `3`.
It means jest will stop running when facing expect function and pass direcly.
It should run the expect and return false to make the testing failed.

**Environment:**

`dependencies`:
- "@angular/animations": "^11.2.0",
-   "@angular/common": "^11.2.0",
-   "@angular/compiler": "^11.2.0",
-   "@angular/core": "^11.2.0",
-   "@angular/forms": "^11.2.0",
-   "@angular/platform-browser": "^11.2.0",
-   "@angular/platform-browser-dynamic": "^11.2.0",
-   "@angular/router": "^11.2.0",
-   "@apollo/client": "^3.3.11",
-   "@nrwl/angular": "11.4.0",
-   "apollo-angular": "^2.3.0",
-   "graphql": "^15.5.0",
-   "rxjs": "~6.6.3",
-   "tslib": "^2.0.0",
-   "zone.js": "^0.10.2"

`devDependencies`:
 - "@angular-devkit/build-angular": "~0.1102.0",
 -  "@angular-eslint/eslint-plugin": "~1.0.0",
 -  "@angular-eslint/eslint-plugin-template": "~1.0.0",
 -  "@angular-eslint/template-parser": "~1.0.0",
 -  "@angular/cli": "~11.0.0",
 -  "@angular/compiler-cli": "^11.2.0",
 -  "@angular/language-service": "^11.2.0",
 -  "@nrwl/cli": "11.4.0",
 -  "@nrwl/cypress": "11.4.0",
 -  "@nrwl/eslint-plugin-nx": "11.4.0",
 -  "@nrwl/jest": "11.4.0",
 -  "@nrwl/linter": "11.4.0",
 -  "@nrwl/tao": "11.4.0",
 -  "@nrwl/workspace": "11.4.0",
 -  "@types/jest": "26.0.8",
 -  "@types/node": "12.12.38",
 -  "@typescript-eslint/eslint-plugin": "4.3.0",
 -  "@typescript-eslint/parser": "4.3.0",
 -  "cypress": "^6.0.1",
 -  "dotenv": "6.2.0",
 -  "eslint": "7.10.0",
 -  "eslint-config-prettier": "6.0.0",
 -  "eslint-plugin-cypress": "^2.10.3",
 -  "jest": "26.2.2",
 -  "jest-preset-angular": "8.3.2",
 -  "prettier": "2.2.1",
 -  "ts-jest": "26.4.0",
 -  "ts-node": "~9.1.1",
 -  "typescript": "~4.0.3"

**Additional context**

here is my sample [repo](https://github.com/tso1158687/apollo-angular-with-jest.git)
the file is in the `apollo-angular-with-jest/apps/apollo-angular/src/app/graphql.service.spec.ts`

**Comment by fetis** [comment]
@tso1158687 strictly speaking `subscribe` is an async operation. did you try it with
`it('should...', done => {})`?

https://jestjs.io/docs/asynchronous

**Comment by vladimirdrayling** [comment]
@tso1158687

```ts
//                             add done
it('should get data from graphql', done => {
  service.getData().subscribe((data) => {
    console.log('1');
    expect(false).toBeTruthy();
    console.log('2');
    expect(1).toBe(2);
    console.log('3');
    done(); // <- add this
  });
  // ...
});
```
