### ISSUE TITLE
[lazy load] Client has not been defined yet

### ISSUE THREAD

**Issue by esdegan50000** [kamilkisiela/apollo-angular#1640]
**Describe the bug**

Got "Client has not been defined yet" when use lazy load feature module

**To Reproduce**

**Expected behavior**

work as well as eager load feature module

**Environment:**

- `@apollo/client`:3.0.0
- `apollo-angular`:2.4.0
- `graphql`:15.0.0
- `@angular/core`:11.0.5
- `@angular/cli`:11.0.7
- `typescript`:4.0.2

**Additional context**

maybe related with https://github.com/kamilkisiela/apollo-angular/pull/1586

**Comment by kamilkisiela** [comment]
Yes it's related to #1586 , I didn't have time to work on it yet
