### ISSUE TITLE
Support angular 12

### ISSUE THREAD

**Issue by MikaStark** [kamilkisiela/apollo-angular#1669]
**Describe the bug**

Hello :)
`apollo-angular` has a peer dependency to @angular/core@"^6.1.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0". It will be great if it can accept the new angular 12 version

**To Reproduce**

Update to angular 12 and try to install apollo-angular (or update it). You will get :

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^6.1.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0" from apollo-angular@2.4.0
npm ERR! node_modules/apollo-angular
npm ERR!   apollo-angular@"^2.4.0" from the root project
```

**Environment:**

```
├── @angular/cli@12.0.0
├── @angular/core@12.0.0
├── @apollo/client@3.3.19
├── apollo-angular@2.4.0
├── graphql@15.5.0
└── typescript@4.2.4
```

**Additional context**

Thanks for your work :)

**Comment by damingerdai** [comment]
i still use  apollo-angular 1.x. cloud we add the angular 12 support for v1.x?

**Comment by celvin** [comment]
I also have this issue with Angular 11

Could not resolve dependency:
npm ERR! peer @angular/common@"^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0" from apollo-angular-link-http-common@1.10.0
npm ERR! node_modules/apollo-angular-link-http-common
npm ERR!   apollo-angular-link-http-common@"^1.10.0" from the root project

**Comment by PhilippS93** [comment]
also experiencing this error

**Comment by kamilkisiela** [comment]
[`v2.5.0`](https://github.com/kamilkisiela/apollo-angular/releases/tag/v2.5.0)

**Comment by kamilkisiela** [comment]
@celvin http link is now under `apollo-angular/http`
