### ISSUE TITLE
Didn't push last version ?

### ISSUE THREAD

**Issue by PowerKiKi** [kamilkisiela/apollo-angular#1678]
**Describe the bug**

https://github.com/kamilkisiela/apollo-angular/blob/master/packages/apollo-angular/CHANGELOG.md does not mention at all the latest version https://github.com/kamilkisiela/apollo-angular/releases/tag/v2.6.0

**Expected behavior**

I expect to see "2.6.0" in the changelog, and possibly other changes that were not pushed either.

**Additional context**

I suppose you forgot to `git push`.

Also it seems that you create GitHub releases automatically based on pushed tags. I would suggest the same to publish to npm. So one `git push` do the entire release process and the public git repo is the single source of truth.

**Comment by kamilkisiela** [comment]
it's under `version-2` branch and here

![Zrzut ekranu 2021-05-31 o 18 08 47](https://user-images.githubusercontent.com/8167190/120219338-60556400-c23b-11eb-85f8-cffaf9fd1f28.png)

you can click on a tag or commit
