### ISSUE TITLE
TypeScript error code TS2614

### ISSUE THREAD

**Issue by luismendes070** [kamilkisiela/apollo-angular#1682]
**Describe the bug**

npm run start

**To Reproduce**

**Expected behavior**

**Environment:**

```
- @angular/cli@12.0.1
- @angular/core@12.0.1
- @apollo/client@3.3.19
- apollo-angular@2.6.0
- graphql@15.5.0
- typescript@4.2.4
```

**Additional context**

[https://gist.github.com/luismendes070/59d362bf7bbb38c50d8dea2149b07653](url)

**Comment by fetis** [comment]
```
Error: node_modules/@apollo/client/core/index.d.ts:14:10 - error TS2614: Module '"ts-invariant"' has no exported member 'setVerbosity'. Did you mean to use
          
        'import setVerbosity from "ts-invariant"' instead?
        14 import { setVerbosity } from "ts-invariant";
```

The error relates to Apollo Client itself, not to Apollo Angular.  I suggest openning issue in corresponding repo https://github.com/apollographql/apollo-client
