### ISSUE TITLE
Apollo Angular did not apply the existing http interceptor

### ISSUE THREAD

**Issue by hantsy** [kamilkisiela/apollo-angular#1691]
The original question is posted on the stackoverflow,  but I can not find a solution to overcome this.
there is [an example can be used to produce it](https://github.com/hantsy/nestjs-graphql-sample/blob/master/ui/).

I added an angular client to interact with the GraphQL backend. 

In this Angular project, I used [Apollo Angular](https://apollo-angular.com) to send queries, and I also used [Auth0 Angular SDK](https://auth0.github.io/auth0-angular/) to handle the authentication and authorization. 

I followed the official Apollo Angular guide to add a [`GraphQLmodule`](
https://github.com/hantsy/nestjs-graphql-sample/blob/master/ui/src/app/core/graphql.module.ts), I have to add the `Authorization` header myself.

The [original HTTP Interceptors](https://github.com/hantsy/nestjs-graphql-sample/blob/master/ui/src/app/app.module.ts#L82) which works in Http/Rest case did not work here.

I think Apollo Angular is also dependent on the Angular `HttpClientModule`, but why I have to set the  `Authorization` manually?

**Comment by jcardoz** [comment]
@hantsy @kamilkisiela - were you able to resolve this issue. I am running an Angular 12 project. We were using standard HTTP calls - but have now made the move to graphQL. However, my interceptor does not work on the GraphQL requests. Is there a sample implementation which is able to intercept graphQL requests like standard GET and POST requests?

**Comment by PowerKiKi** [comment]
See https://stackblitz.com/edit/stackblitz-starters-phryss?file=src%2Fmain.ts for an example of working HTTP interceptor with apollo-angular. The trick is to use `HttpLink` from `apollo-angular/http` (because it will use Angular's `HttpClient`), and to provide `HttpClient` correctly, meaning it is "visible" the apollo-angular (so if you provide all of those at the root of your app, you should be fine).

```ts
import { Component, inject } from '@angular/core';
import { JsonPipe } from '@angular/common';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { bootstrapApplication } from '@angular/platform-browser';
import { Apollo, APOLLO_OPTIONS, gql } from 'apollo-angular';
import { HttpLink } from 'apollo-angular/http';
import { ApolloClientOptions, InMemoryCache } from '@apollo/client/core';

function apolloOptionsFactory(): ApolloClientOptions<any> {
  const httpLink = inject(HttpLink);
  return {
    link: httpLink.create({
      uri: 'https://swapi-graphql.netlify.app/.netlify/functions/index',
    }),
    cache: new InMemoryCache(),
  };
}

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <h1>HTTP interceptor with apollo-angular</h1>
    <p>Open the console to see intercepted requests.</p>
    <p>Result:</p>
    <pre>{{ result |json }}</pre>
  `,
  imports: [JsonPipe],
})
export class App {
  result: any = null;

  constructor(apollo: Apollo) {
    apollo
      .query({
        query: gql`{
        allFilms {
          films {
            title
          }
        }
      }`,
      })
      .subscribe((result) => (this.result = result));
  }
}

bootstrapApplication(App, {
  providers: [
    provideHttpClient(
      withInterceptors([
        (req, next) => {
          console.warn('Intercepted request:', req);

          return next(req);
        },
      ])
    ),
    Apollo,
    {
      provide: APOLLO_OPTIONS,
      useFactory: apolloOptionsFactory,
    },
  ],
});
```
