### ISSUE TITLE
Incompatible typing with `graphql^16.0.0` produces `error TS2430: Interface 'SubscriptionResult<TData>' incorrectly extends interface 'ExecutionResult<ObjMap<unknown>, ObjMap<unknown>>'.`

### ISSUE THREAD

**Issue by KeithGillette** [kamilkisiela/apollo-angular#1723]
**Describe the bug**
When attempting to update an `apollo-angular` project to `graphql^16.0.0` project transpilation produces `error TS2430: Interface 'SubscriptionResult<TData>' incorrectly extends interface 'ExecutionResult<ObjMap<unknown>, ObjMap<unknown>>'.`:

```
Error: node_modules/apollo-angular/types.d.ts:30:18 - error TS2430: Interface 'SubscriptionResult<TData>' incorrectly extends interface 'ExecutionResult<ObjMap<unknown>, ObjMap<unknown>>'.
  Types of property 'data' are incompatible.
    Type 'TData' is not assignable to type 'ObjMap<unknown>'.

30 export interface SubscriptionResult<TData> extends ExecutionResult {
                    ~~~~~~~~~~~~~~~~~~
```

**To Reproduce**
Run `tsc` on project depending on `apollo-angular@2.6.0` & `graphql^16.0.0` with a `tsconfig.json` observing the default` skipLibCheck: false`.

**Expected behavior**
Updating to `graphql^16.0.0` should work without error.

**Environment:**
```
├── @angular/cli@13.0.3 
├── @angular/core@13.0.2 
├── @apollo/client@3.5.3 
├── @types/graphql@14.5.0
├── apollo-angular@2.6.0 
├── graphql@16.0.1 
└── typescript@4.4.4 
```

**Additional context**
The bug description has been updated to correct the original incorrect attribution of this typing error to upgrading `@apollo/client^3.5.0` when in fact the upgrade causing the problem was from `graphql@15.7.2` to `graphql@16.0.1`.

**Comment by Urigo** [comment]
Hi @KeithGillette and thank you for the report!

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems already got into `stage 0`.

Now in order to advance to `stage 1` we'll need a simple reproduction, maybe in code-sandbox? 

Later to progress to `stage 2`, a failing test would be needed, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by russcarver** [comment]
Same issue for me.

**Comment by orr3** [comment]
Same here. Fresh install following the readme.

```
npm i apollo-angular @apollo/client graphql
ng build
```
**Fails because we're getting graphql@16** 

```
npm i apollo-angular @apollo/client graphql^15
ng build
```
**Works**

**Comment by KeithGillette** [comment]
@Urigo or @kamilkisiela —

Thanks for your work on this library. Are @orr3 's [reproduction instructions](https://github.com/kamilkisiela/apollo-angular/issues/1723#issuecomment-974047180) sufficient to move this issue to Stage 1? If not, please point me to a working starter project using `apollo-angular@2.6.0` that I can fork and update to `graphql^16.0.0` to publicly demonstrate the incompatibility.

**Comment by vslipchenko** [comment]
Created a draft PR #1739

**Comment by BaryshevRS** [comment]
It temporary solution for Angular 13 and apollo-angular@2.6.0.

`npm i apollo-angular @apollo/client graphql@^15 --legacy-peer-deps`

Fix types:
`npm i -D @types/react react`

And add to tsconfig.json:

` "allowSyntheticDefaultImports": true,`

**Comment by sebastienvermeille** [comment]
Same here unfortunately still not working on a fresh angular project :/ I hope someone can find a solution.

I get errors with the fix you propose @BaryshevRS (Cannot find namespace JSX and so on... I will retry but if you pass here maybe yo have an idea?)

**Comment by danielaltamarb** [comment]
Hello, did you solved this issue? i have the latest versions and got the same error

**Comment by KeithGillette** [comment]
Yes, this incompatibility with the GraphQL 16 types was resolved with the release of Apollo Angular 3. There are new typing issues with Apollo Angular 4 and Apollo Client, per #1810 & #1818, but they are different from this issue.
