### ISSUE TITLE
Getting legacy "View Engine" warning with Angular ^13.1

### ISSUE THREAD

**Issue by jponeill** [kamilkisiela/apollo-angular#1732]
**Describe the bug**

Angular has deprecated support for legacy "View Engine" support and now gives the following warning when building an apollo-angular project using Angular 13.1 pre-release. 

Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- apollo-angular [es2015/esm2015] (https://github.com/kamilkisiela/apollo-angular)
- apollo-angular/http [es2015/esm2015] (https://github.com/kamilkisiela/apollo-angular)

**To Reproduce**

Install angular/cli@13.1.0-next.2
ng new test
cd test
ng add apollo-angular
ng build 

.... gives following warning:
Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- apollo-angular [es2015/esm2015] (https://github.com/kamilkisiela/apollo-angular)
- apollo-angular/http [es2015/esm2015] (https://github.com/kamilkisiela/apollo-angular)

**Expected behavior**

No warning.

**Environment:**

 @angular/cli@13.1.0-next.2
├── @angular/core@13.1.0-next.2
├── @apollo/client@3.4.17
├── apollo-angular@2.6.0
├── graphql@15.7.2
└── typescript@4.5.2

**Additional context**

**Comment by kamilkisiela** [comment]
#1729
