### ISSUE TITLE
Update @apollo/client to >=3.4 to support refetchQueries

### ISSUE THREAD

**Issue by FinnStutzenstein** [kamilkisiela/apollo-angular#1738]
Currently @apollo/client 3.3 is used. It would be nice to update and support `refetchQueries` (https://www.apollographql.com/docs/react/data/refetching/), which should be implemented in the `ApolloBase` if I'm correct here.

**Comment by kamilkisiela** [comment]
@FinnStutzenstein just call it from client directly
```typescript
apollo.client.refetchQueries(...)
```
