### ISSUE TITLE
ng add apollo-angular not work with angular 13

### ISSUE THREAD

**Issue by UchihaYuki** [kamilkisiela/apollo-angular#1754]
A fix needed, the error I got is
```
peer @angular/core@"^6.1.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0" from apollo-angular@2.6.0
```

**Comment by risc-bschenke** [comment]
Same here. Please advise!

**Comment by acuevas91** [comment]
In order to use Angular 13, you need to upgrade `apollo-angular` dependency to an alpha version: `3.0.0-alpha.2`

**Comment by anymos** [comment]
Hi there any idea when the 3.0.0 version will be available officially ? any ETA in mind ?

**Comment by risc-bschenke** [comment]
It worked using `npm install https://github.com/kamilkisiela/apollo-angular.git#master --save`. Thank you!

**Comment by alkamishra20** [comment]
Its throwing error for me while using version 3.0.0-alpha.2. 

ERROR -  NullInjectorError: No provider for Apollo!

**Comment by Cito** [comment]
> ERROR - NullInjectorError: No provider for Apollo!

You have to add Apollo to the list of providers in the Angular module.
