### ISSUE TITLE
flag incorrect query and mutations on compilation

### ISSUE THREAD

**Issue by hexdecimal16** [kamilkisiela/apollo-angular#1766]
How can I flag incorrect queries and mutations during compilation? 

Since query and mutation are essentially strings how safe are they to use, because and change in schema can't be refected clearly on those queries.

**Comment by kamilkisiela** [comment]
What do you mean by "flag" and could you elaborate a bit more and even share some examples?

**Comment by hexdecimal16** [comment]
Example:
schema
```
type User {
  id: String!
  username: String!
  balance: Float!
  amountAdded: Float!
}
type Query {
 """Returns a user by id"""
  user(): [User]
}
```
query
```
const GET_USERS = gql`query User {
  user {
    username
  }
}`
```
Now suppose I rename username to name on my backend. How will frontend while building know that this query is wrong now. There should be some flag that can warn or throw error while building/compilation.
@kamilkisiela

**Comment by kamilkisiela** [comment]
There are tools for that, like GraphQL Inspector to validate documents against the schema or GraphQL Code Generator to generate TypeScript types and interfaces.
https://www.the-guild.dev/blog/graphql-with-typescript-done-right

https://the-guild.dev/blog/new-graphql-inspector

**Comment by hexdecimal16** [comment]
> There are tools for that, like GraphQL Inspector to validate documents against the schema or GraphQL Code Generator to generate TypeScript types and interfaces. https://www.the-guild.dev/blog/graphql-with-typescript-done-right
> 
> https://the-guild.dev/blog/new-graphql-inspector

I think it will be more beneficial if we have it in the client instead of adding more 3rd party dependency in the project

**Comment by PowerKiKi** [comment]
The modern solution is to use https://the-guild.dev/graphql/codegen

**Comment by hexdecimal16** [comment]
Thanks @PowerKiKi will look into this
