### ISSUE TITLE
Updating to apollo-angular v3 and angular v13 get NullInjectorError Apollo

### ISSUE THREAD

**Issue by UchihaYuki** [kamilkisiela/apollo-angular#1769]
I looked at source code, the decorator for Apollo class is :
```
@Injectable()
```
Shouldn't it be:
```
@Injectable({
  providedIn: 'root',
})
```
I looked in history it is:

```
@Injectable({
  providedIn: 'root',
})
```
Any reason here?

**Comment by amakhrov** [comment]
Looks like it's intentional:
https://apollo-angular.com/docs/migration#apollomodule

**Comment by kamilkisiela** [comment]
It's described in the changelog and the migration doc that ApolloModule is back and why
