### ISSUE TITLE
Compile Error in generated code: "TS414 must use override"

### ISSUE THREAD

**Issue by tmtron** [kamilkisiela/apollo-angular#1800]
**Describe the bug**

The generated code does not compile:

`TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Mutation<ConfigUpsertMutation, Exact<{ data: ConfigCreateInput; }>>'.`

This happens because the `document` property in the generated Mutation overrides the document property of the parent ` Apollo.Mutation` class

![image](https://user-images.githubusercontent.com/20422904/177999163-639b7ec6-121c-4ed3-94a1-b14e321c81c6.png)

**To Reproduce**

in `tsconfig.json` set `"noImplicitOverride": true`

**Expected behavior**

should compile

**Environment:**

```
+-- @angular/cli@13.1.2 
+-- @angular/core@13.1.1
+-- @apollo/client@3.6.8
+-- apollo-angular@3.0.1
+-- graphql@16.5.0
`-- typescript@4.5.4

```

**Comment by synerp** [comment]
Did you end up fixing this?

**Comment by tmtron** [comment]
@synerp No. As  a workaround I've set `"noImplicitOverride": false` in `tsconfig.json` until this is fixed

**Comment by synerp** [comment]
@tmtron have you tried this option?

config:
  addExplicitOverride: true

**Comment by tmtron** [comment]
@synerp Thanks, that works. I was not aware of this config option.

After enabling the [`addExplicitOverride` config option](https://www.graphql-code-generator.com/plugins/typescript/typescript-apollo-angular#:~:text=addExplicitOverride,-%23) of typescript-apollo-angular plugin generated code also works when `noImplicitOverride` is `true`.

I've added the [config at the plugin-level](https://www.graphql-code-generator.com/docs/config-reference/config-field#plugin-level) of my `codegen.yml`
```yml
generates:
  ./libs/`XXX/generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular:
          addExplicitOverride: true
```
