### ISSUE TITLE
Apollo Angular 4.0 `QueryRef.fetchMore` parameter typings remove `updateQuery` property

### ISSUE THREAD

**Issue by KeithGillette** [kamilkisiela/apollo-angular#1810]
**Describe the bug**
Upgrading from `apollo-angular@3.0.1` to `apollo-angular@4.0.1` produces TS2345 error on code which passes an `updateQuery` property to  the `fetchMoreOptions` parameter of a `QueryRef.fetchMore`call.

**To Reproduce**
Previously, the `QueryRef.fetchMore` `fetchMoreOptions` parameter was typed with `FetchMoreQueryOptions` & `FetchMoreOptions` but [Apollo Angular 4 removed `FetchMoreOptions` and with it the `updateQuery` property on the parameter](https://github.com/kamilkisiela/apollo-angular/commits/6ba15daa8ac3dc81f9077be9cc1d8ea862b0ef89/packages/apollo-angular/src/query-ref.ts#diff-b47d97e5d55211e2025f70dfb7e7eb7e5d41788be0e28eb52d5df652d06199f8L103).

**Expected behavior**
The method signature should not change, since [the underlying Apollo Client `ObservableQuery.fetchMore` method still has `updateQuery` in its signature](https://github.com/apollographql/apollo-client/blob/main/src/core/ObservableQuery.ts#L391).

**Environment:**
```
├── @angular/cli@14.1.3 
├── @angular/core@14.1.3 
├── @apollo/client@3.6.8 
├── apollo-angular@4.0.1 
├── barrel-maintainer@1.5.3
├── graphql@16.5.0 
└── typescript@4.7.4 
```

**Additional context**
That pretty much sums it up.

**Comment by KeithGillette** [comment]
Finding that this typing issue still exists in release 4.1.0, I investigated further and found that while `updateQuery` is still supported Apollo Client 3, [it is deprecated](https://github.com/apollographql/apollo-client/pull/6464) and [will be removed in the next major version of Apollo Client](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-300), so while its removal in Apollo Angular 4 may be somewhat premature, it is inevitable. I refactored our use of `updateQuery` (merging paginated results) to use the Apollo Client recommended solution of adding [a field policy with a merge function](https://www.apollographql.com/docs/react/pagination/core-api/#merging-paginated-results).

**Comment by alfaproject** [comment]
@KeithGillette I have a dynamic helper that creates a dynamic `updateQuery` to avoid repetition, something like this:
```ts
      updateQuery: (prev, { fetchMoreResult }) => {
        if (!fetchMoreResult) {
          return prev;
        }

        const newEdges = fetchMoreResult[this.connectionFieldName].edges;
        if (newEdges.length === 0) {
          return prev;
        }

        return {
          [this.connectionFieldName]: {
            ...fetchMoreResult[this.connectionFieldName],
            edges:
              this.direction === Direction.ASCENDING
                ? [...prev[this.connectionFieldName].edges, ...newEdges]
                : [...newEdges, ...prev[this.connectionFieldName].edges],
          },
        };
      },
```

Are you telling me that we now need to go to our cache adaptor and add type policy for each individual connection. We have hundreds of them and each one is 'owned' by a particular service which is agnostic to the cache o.o

**Comment by jwrascoe** [comment]
@KeithGillette I also do the same as you with respect to a dynamic helper.... I cant seem to figure out get a simple policy merge working let alone a dynamic one have you? 

For now I put in the a @ts-ignore and im working fine on the latest but somehow need to figure out this policy merge.

My existing super simple merge that works fine.

        updateQuery: (prev, { fetchMoreResult }) => {
          if (!fetchMoreResult) {
            return prev;
          }
          fetchMoreResult.allProducts.edges = [
            ...prev.allProducts.edges,
            ...fetchMoreResult.allProducts.edges
          ];
          return fetchMoreResult;
        }
      }

I would think something like this would work.. but incoming is always null and not iterable

    cache: new InMemoryCache({
      typePolicies: {
        Query: {
          fields: {
            allProducts: {
              keyArgs: false,
              merge(existing = [], incoming) {
                console.log('I need to figure out how to merge');
                return [...existing, ...incoming];
              }
            }
          }
        }
      }
    })

**Comment by KeithGillette** [comment]
@jwrascoe — I'm not sure why the `incoming` argument would always be null in your case. The field policy merges we're using are either integrating skip/limit or page-based pagination results, not relay-style cursors. We're using basically a copy/paste of the [sample `merge` functions on the Apollo documentation](https://www.apollographql.com/docs/react/pagination/core-api/#improving-the-merge-function).

**Comment by jwrascoe** [comment]
@KeithGillette -- yes its strange, I have been using Apollo since its early inception against a postgres via PostGraphile and have never had a situation like this before, perhaps its related to how edges are returned or that I am calling only with a limit and offset from a cursor

So strange...

--Forgive me on the formatting.. not sure why its getting messed up in git

  fetchDataMore() {
    this.productQuery.fetchMore({
      variables: {
        limit: 8,
        offset: this.searchResults.edges.length
      }
    });
  }



query allProductsByClientIdForSearchMore(
  $offset: Int
  $limit: Int
) {
  allProducts(
    orderBy: NAME_ASC
    offset: $offset
    first: $limit

  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      cursor
      node {
        id
        name
        price
      }
    }
  }
}

**Comment by SeregPie** [comment]
https://github.com/apollographql/apollo-client/issues/8915#issuecomment-2264157648

Would be nice to have `updateQuery` in the types back.
