### ISSUE TITLE
Cannot use subscriptions with the newest version of apollo-angular

### ISSUE THREAD

**Issue by jfsubi** [kamilkisiela/apollo-angular#1813]
As it is said in the title, I cannot use subscriptions with the newest version of apollo-angular. I saw a subscriptions-transport-ws is not used anymore. What to do with that?
Thanks for reply.

**Comment by KeithGillette** [comment]
I believe this is a duplicate of #1801. The solution is to use `graphql-ws` instead of `subscriptions-transport-ws`.
