### ISSUE TITLE
Support newest zone.js

### ISSUE THREAD

**Issue by de-dan** [kamilkisiela/apollo-angular#1841]
https://github.com/kamilkisiela/apollo-angular/blob/d1f4b4075d69c8af5e400a1a91a910ee6dab9d4e/packages/apollo-angular/package.json#L43

The current release of Apollo Angular doesn't support zone.js 0.12.0 because of this peerDependency. Before setting a new boundary for the zone.js version consider removing it from the list of peerDependency if it is not used / or remove the upper boundary. I don't see a reason why this lib should limit the zone.js version.

Also consider Angular's plans to make zone.js optional -> This lib shouldn't be dependent on zone.js, for the sake of future proof.

**Comment by marcos-castrillo** [comment]
+1, our project has encountered the same issue.
