### ISSUE TITLE
Issues with v4.1.1

### ISSUE THREAD

**Issue by elliotleelewis** [kamilkisiela/apollo-angular#1855]
### Discussed in https://github.com/kamilkisiela/apollo-angular/discussions/1852

<div type='discussions-op-text'>

<sup>Originally posted by **KillerCodeMonkey** November 21, 2022</sup>
heyho,

instead of creating a bug, i just first wanna ask, if this build/release was wrongly published?

seems like you released the whole project and not only the build- folder.

Am i right?</div>

**Comment by PowerKiKi** [comment]
I am assuming this should be solved by 4.2.0. Re-open if that's not the case.

**Comment by elliotleelewis** [comment]
Can confirm, looks like it has been resolved. Thank you!
