### ISSUE TITLE
apollo-angular 4.1.1 installation failed

### ISSUE THREAD

**Issue by Fedpaf** [kamilkisiela/apollo-angular#1871]
The installation failed cause I have angular/core 15.0.0. If I force the installation it works fine. This is annoying.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/32685682/209701546-6bbc73ab-aba7-41b5-aaa4-8aad70edb80e.png">

**Comment by SimonCockx** [comment]
This is already resolved on master, but just needs publishing to `npm`. See discussion in https://github.com/kamilkisiela/apollo-angular/issues/1847

Temporary workaround until the maintainer makes a new release: add this to your `package.json`.
```
"overrides": {
        "apollo-angular": {
            "@angular/core": "^15.0.0"
        }
    },
```

**Comment by PowerKiKi** [comment]
Duplicate of #1847

**Comment by Fedpaf** [comment]
Thank you for the reply. The workaround worked successfully.
