### ISSUE TITLE
https://the-guild.dev/graphql/apollo-angular/ broken

### ISSUE THREAD

**Issue by mafalarz** [kamilkisiela/apollo-angular#1875]
Unable to read any documentation on apollo angular because the website is broken with error:

This site can’t provide a secure connectionthe-guild.dev uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by PowerKiKi** [comment]
Cannot reproduce on Chrome or Firefox. Might have been temporary.

![image](https://user-images.githubusercontent.com/72603/210482448-5cdc75fb-c21d-4a49-b800-8a6293697c36.png)


![image](https://user-images.githubusercontent.com/72603/210482382-32d5cbd5-628a-4446-9fad-e1d58e705653.png)
