### ISSUE TITLE
GraphQL cache unable to detect the changes in query

### ISSUE THREAD

**Issue by watashiwaTXT** [kamilkisiela/apollo-angular#1949]
**Describe the bug**

When first search with value:  \"%ACTIVE                XX%\" (Multiple space in between)
The console shows that the query is queried correctly.

But when continued to search with value: \"%ACTIVE XX%\" (Single space in between)
The console still shows that it query using the data as the first query.

**To Reproduce**

Just as described in the bug description, just search with query with lots of space in between "XX          XX",
Then subsequent search with same data but with single space in between only "XX XX".

**Expected behavior**

The cache detection should be able to detect that the two search query are different. (Space in between)

**Environment:**

```
- @angular/cli@12.2.13
- @angular/core@12.2.13
- @apollo/client@3.0.0
- apollo-angular@2.5.0
- graphql@15.0.0
- typescript@4.3.5
```

**Additional context**
https://imgur.com/a/quv1jhG

**Comment by PowerKiKi** [comment]
"just search with query", search where ? You give no code at all, no reproduction case.

There is no way anybody could help you.
