### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by Maximaximum** [kamilkisiela/apollo-angular#2008]
**Describe the bug**

Do you plan to add support for Angular 16? And for Angular `standalone component` methods like `bootstrapApplication()`

Thank you.

**Comment by PowerKiKi** [comment]
Feel free to create PR for each of those. Angular 16 is probably easy-ish. Standalone might require a bit more work, but anybody is welcome to give it a try

**Comment by fromsomnia** [comment]
Linking PR by @PowerKiKi https://github.com/kamilkisiela/apollo-angular/pull/2009

**Comment by fromsomnia** [comment]
#2009 superseded by https://github.com/kamilkisiela/apollo-angular/pull/2010

**Comment by fromsomnia** [comment]
#2010 merged into upcoming release changes: https://github.com/kamilkisiela/apollo-angular/pull/2014

**Comment by PowerKiKi** [comment]
@fromsomnia please refrain from posting those kind of updates. If people are interested they will follow the issues/pr themselves.

**Comment by PowerKiKi** [comment]
Apollo 16 support was added in the just released [v5.0.0](https://github.com/kamilkisiela/apollo-angular/releases/tag/apollo-angular%405.0.0).

Nothing specific was done for standalone app. But they can already use apollo-angular as long as they provides it correctly. Support for automatically adding apollo-angular to an existing standalone app via schematics will come later. If somebody submit a PR for it...
