### ISSUE TITLE
Angular 17 support

### ISSUE THREAD

**Issue by supermakdas** [kamilkisiela/apollo-angular#2090]
**Describe the bug**

A peer dependency conflict with apollo-angular@5.0.2.

Using Angular version 17 (@angular/core@17.0.1), apollo-angular@5.0.2 expects a peer of Angular core version 14, 15, or 16 (@angular/core@"^14.0.0 || ^15.0.0 || ^16.0.0"). 

The apollo-angular package requires a version of Angular core that is not higher than 16.

**To Reproduce**

with Angular cli 17
ng new 
npm i apollo-angular

**Expected behavior**

npm install of Apollo-angular

**Comment by rezoled** [comment]
Added a PR for Angular 17 - https://github.com/kamilkisiela/apollo-angular/pull/2094

**Comment by HoseinGhanbari** [comment]
UP ⬆️

Angular 17 support is highly required ⚡️
