### ISSUE TITLE
Feedback for “Get Started” >  "Installation without Angular Schematics"

### ISSUE THREAD

**Issue by tomshanan** [kamilkisiela/apollo-angular#2256]
The section on "Installation without Angular Schematics" is full of errors and mistakes, and not enough explanation on how to configure it,
This section specifically returns a type error, as `httpLink.create` is not a function.
```
{
      provide: APOLLO_OPTIONS,
      useFactory(httpLink: HttpLink) {
        return {
          cache: new InMemoryCache(),
          link: httpLink.create({
            uri: 'https://48p1r2roz4.sse.codesandbox.io',
          }),
        };
      },
      deps: [HttpLink],
    },
```
![Screenshot 2024-05-21 153249](https://github.com/kamilkisiela/apollo-angular/assets/41544662/df6628a0-851c-4f49-861a-36339535763b)

the lines following do not explain how to configure it correctly, and the sentences are incomplete.
This needs refining and updating

**Comment by PowerKiKi** [comment]
Feel free to create a PR do update documentation

**Comment by tomshanan** [comment]
The issue was that I couldn't follow the docs, and you expect me to update the docs? If I knew how to update the docs I probably wouldn't need to use them in the first place.
