### ISSUE TITLE
Apollo Client Update: Usage of GraphQLFormattedError instead of GraphQLError and others.

### ISSUE THREAD

**Issue by ratheeshaditya** [kamilkisiela/apollo-angular#2311]
Hi, 
I have updated my Apollo Client. And have been facing issues based to this update https://github.com/apollographql/apollo-client/releases in Apollo Angular. Where, the usage of GraphQLError type was incorrect and GraphQLFormattedError should be used, and similarly for ExecutionResult where FormattedExecutionResult should be used.

**Comment by PowerKiKi** [comment]
There is no useful information in this message, and thus there is nothing we can do at all. If you saw a bug, create a minimal, working, reproduction case. If you have a general question or need help on how to use the library, [start a discussion about it](https://github.com/kamilkisiela/apollo-angular/discussions).
