### ISSUE TITLE
FR: async client creation

### ISSUE THREAD

**Issue by amitport** [kamilkisiela/apollo-angular#569]
In some situations it's not possible to create a client synchronously (e.g., the options for apollo.create are unknown and we need to make an introspection request). In those situations it would be nice that Apollo client's methods (e.g., 'watchQuery`) will try and wait for the client creation. For example:

```
// allow async client option
apollo.create( Observable | Promise | ApolloClientOptions<TCacheShape>, name?: string)  

apollo.watchQuery // works as before but waits for the client creation (with Observable | Promised client options)
```

**Comment by kamilkisiela** [comment]
I will keep that in mine while planning next tasks in Apollo angular

**Comment by kamilkisiela** [comment]
In most cases you can use `APP_INITIALIZER`. It handles async stuff which might be helpful for things like `apollo-cache-persist`. I won't implement this lazy client creation on my own because I don't have such use-cases in my projects so I will leave that to the community.

```ts
{
  provide: APP_INITIALIZER,
  multi: true,
  useFactory: () => () => persistCache(),
}
```

**Comment by kamilkisiela** [comment]
You can write a service that handles client creation and wraps an observable
