### ISSUE TITLE
Error in apollo-angular-link-http-batch when changing headers

### ISSUE THREAD

**Issue by Dragons0458** [kamilkisiela/apollo-angular#771]
Hello! when I try to change the headers of my requests to be able to put the apollo-angular-link-http-batch token it gives me an error which I do not get with apollo-angular-link-http. This is my code:

```
const http = from([
     setContext((operation, {headers}) => observableToPromise(angularFireAuth.idToken.pipe(
        map(token => ({
          headers: {
            ...headers,
            Authorization: token ? `Bearer ${token}` : null
          }
        }))
      ))),
      onError(error => store.dispatch(new actions.ChangeErrorAction(error))),
      httpBatchLink.create({
        uri: `${environment.http}://${rootPath}`
      })
    ]);
```

This is the error:
![imagen](https://user-images.githubusercontent.com/3160847/44564688-3cbf6f80-a719-11e8-958b-86c94d7906bf.png)

When I change the httpBatchLink variable to httpLink everything works normal, is it a bug in the library? Thank you very much!

**Comment by kamilkisiela** [comment]
Should fix it #1368
